cibernox/ember-power-select

blueprints/ember-power-select/files/app/styles/app.scss, tests/dummy/app/templates/docs/installation.hbs
I've confirmed that, if there is already an `app.scss` file in the project, ember-cli will prompt:
```bash
installing ember-power-select
[?] Overwrite app/styles/app.scss? (Yndh) 
```
=> add scss file blueprint. add installation instructions. closes #7

app/styles/ember-power-select.scss, app/styles/ember-power-select/themes/bootstrap.scss, index.js, tests/dummy/app/templates/cookbook/bootstrap-theme.hbs, tests/dummy/app/templates/docs/styles.hbs
Done with a configuration option in your app (ember-cli-build.js)
Doing so in the app initialization seemed more reasonable than adding the option in the environment.js because it's not something that depends on the environment.
```
var app = new EmberApp(defaults, {
'ember-power-select': {
theme: 'bootstrap'
}
});
```
=> Allow to use bootstrap theme to non-sass users

addon/components/ember-power-select.js, addon/components/ember-power-select/multiple.js, addon/components/ember-power-select/single.js, tests/dummy/app/controllers/docs/how-to-use-it.js, tests/dummy/app/templates/docs/asynchronous-search.hbs, tests/dummy/app/templates/docs/groups.hbs, tests/dummy/app/templates/docs/how-to-use-it.hbs, tests/dummy/app/templates/docs/multiple-selection.hbs, tests/dummy/app/templates/docs/the-list.hbs, tests/dummy/app/templates/docs/the-search.hbs, tests/dummy/app/templates/docs/the-trigger.hbs, tests/dummy/app/templates/legacy-demo.hbs, tests/integration/components/ember-power-select-test.js
Since a select with no associate action is useless this takes the component
one step further towards explicitness.
Now the component won't do ANYTHING AT ALL when an element is selected, it will relay
completely in the `onchange` action defined by the user. The user has to define that
action and update the `selected` value to propagate the change to the component again.
An assertion has been added to lead the user in the good direction
=> Make `onchange` mandatory.

addon/components/ember-power-select/base.js
If a search action is provided, the addon should not apply any filtering at all. The
serch action is supposed to be in charge of everything
=> Bugfix: Don't apply the filter to the options if a search action is given

addon/components/ember-power-select/base.js
When the user deletes text from the searchbox and it reaches 0, the custom
search function should be invoked too. An empty string is perfectly valid string
and is up to the user to decide what to do (perhaps show everithing, perhaps show nothing)
=> BUGFIX: Trigger custom search when the term is an empty string.

package.json, tests/integration/components/ember-power-select-test.js
Apparently jQuery events are different in many ways than native events, so
this is closer to the actual behavior of the addon in the wild.
Particularly jQuery events don't have a `.defaultPrevented` property to check,
and some upcoming functionalities require this.
Also update the dropdown addon to 0.3.2
=> Trigger native events in tests instead of jQuery

addon/utils/group-utils.js, tests/unit/utils/group-utils-test.js
if the text value that the user is searching for is an integer we need to ensure that its a string before running replacing on it.
=> ensure incoming text is a string

app/styles/ember-power-select.scss, app/styles/ember-power-select/themes/bootstrap.scss, app/styles/ember-power-select/variables.scss, tests/dummy/app/styles/app.scss, tests/dummy/app/templates/cookbook/bootstrap-theme.hbs
This allows more complicated patterns like import the variables,
then change a few of them depending on previously defined variables and then
import the rest of the styles.
Also, refactors styles a bit to allow greater customization:
- Border of the trigger and the dropdown can be customized separatedly.
- Refactor styles to improve the way the dropdown is shown contiguously to
the trigger. Now there isn't a 1px separation between them. Problem is that
there is a glitch only when the dropdown is placed above the content that
disappears when scrolling. Not sure why.
=> Extract variables to it's own file.

addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/multiple/selected.hbs, app/styles/ember-power-select.scss, tests/integration/components/power-select-test.js
=> Fixed disabled behaviour of multiple selects

tests/dummy/app/controllers/cookbook/debounce-searches.js, tests/dummy/app/router.js, tests/dummy/app/templates/cookbook.hbs, tests/dummy/app/templates/cookbook/bootstrap-theme.hbs, tests/dummy/app/templates/cookbook/debounce-searches.hbs, tests/dummy/app/templates/cookbook/navigable-select.hbs, tests/dummy/config/environment.js
Also explain why letting the users debounce the search themselves is
more flexible and doesn't require much extra work, and gives the user
more flexibility like variable times or retries.
Closes #5 for now
=> Add cookbook recipe about debouncing searches

package.json
This bings subpixel precission also when calculation the vertical position
of the dropdown
=> Update to ember-basic-dropdown 0.4.7

CHANGELOG.md, addon/components/power-select/multiple/selected.js, tests/integration/components/power-select-test.js
Tests were passing in phantomjs but the feature was actually broken in real life.
Apparently there is some kind if irregular on how attributes are treated when it's value
is undefined.
Now the placeholder is always present, but when falsey its value is an empty strings. That
behaves consistently across browsers.
=> Fix placeholder in multiple select for good.

addon/components/power-select/base.js, package.json, tests/integration/components/power-select-test.js
After closing a select, the text in the searchbox and the list of options must
go back to they initial state, so next time it's opened all results are shown.
=> Add tests to ensure search is reverted after closing the component

addon/components/power-select/base.js, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/single.hbs, tests/integration/components/power-select-test.js
the `selectedComponent` now receives a `hasPendingPromises` flag that it either true or false and can be used to show a loading spinner or something similar.
=> Enable the selectedComponent to know when things are loading

addon/components/power-select/base.js, addon/components/power-select/multiple.js, addon/components/power-select/multiple/selected.js, addon/components/power-select/single.js, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/multiple/selected.hbs, addon/templates/components/power-select/options.hbs, addon/templates/components/power-select/single.hbs, addon/templates/components/power-select/single/selected.hbs, package.json, tests/integration/components/power-select-test.js
The way compositions was handled was a bit chaotic. That was an internal issue but
still an issue. Some actions received the `dropdown` and other didn't, and
you had to remember to pass the dropdown as last argument to function calls.
This refactor creates a uniform shape for the yielded public API of the component
as follows:
```js
{
state1: 'foo',
state2: 'bar',
...
actions: {
action1: fn,
action2: fn,
...
}
}
```
Each level can use the public API of the nested component as follows:
```hbs
{{!-- in delorean.hbs --}}
{{#flux-condensor as |condensor|}}
{{#with (hash gammaPower=condensor.level actions=(hash goToFuture=(action "travelForward" condensor) goToPast=(action "travelBackwards" condensor))) as |delorean|}}
{{control-panel delorean=delorean year=currentYear}}
{{/with}} …
```
=> Refactor components composition

addon/components/power-select/base.js
This makes possible to want to customize the select to perform the search and only open if there is results. 
Before, opening a dropdown cleared the results, while this is something that must only happen on close, not on open.
=> Fix bug that made that opening a select after a search cleared the results

addon/components/power-select/base.js, tests/integration/components/power-select-test.js
I was able to get a solid test to show the production bug Scott and I found recently ( mentioned in detail using issue #142 )
I could use a little feedback on "where this fits" in the integration test file (to make sure you are happy with it/etc). I also updated the doc string you had above the block (again -unsure if I did this as you expected).
Let me know what I can do to pull this in/ get a beta 4 some time this week :)
=> [BUG]: options did not refresh when empty array proxy was updated

CHANGELOG.md, addon/templates/components/power-select.hbs, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/multiple/selected.hbs, addon/templates/components/power-select/options.hbs, addon/templates/components/power-select/single.hbs, addon/templates/components/power-select/single/selected.hbs, tests/integration/components/power-select-test.js
This enables the user to easily highlight matching results. P.e.
```hbs
{{#power-select options=a selected=b onchange=(action (mut b)) as |option term|}}
{{highlight-substring-helper-or-something option.name term}}
{{/power-select}}
```
=> Yielded block now also receives the search term as second argument

addon/components/power-select/base.js, addon/components/power-select/multiple.js, addon/components/power-select/single.js, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/single.hbs, tests/integration/components/power-select-test.js
The public API is clearly documented, so there is no need to using
underscores for this.
_searchText is no just searchText
_highlighted is now just highlighted
=> Stop underscoring some internal fields.

addon/components/power-select/base.js, addon/components/power-select/multiple.js, addon/components/power-select/single.js, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/single.hbs, addon/utils/group-utils.js, tests/dummy/app/templates/legacy-demo.hbs, tests/integration/components/power-select-test.js
The code is significantly simpler, and also shorter. I haven't measured
but I also hope that being lazy there is some other advantage.
This might be slightly incompatible since the selectedComponent doesn't
receive the hasPendingPromises argument, but the `results` argument is now
a PromiseProxy, so it can check the `isFulfilled` there.
=> Refactor results and highlighted to be a computed property

package.json
The bug was always there but ember 2.2.0 triggered it, perhaps for being
faster or something.
tl;dr; Ember-basic-dropdown has to ensure that the opened dropdown is
closed before the new one opens (otherwise the reposition code will target
the first one).
The solution is to attach the click event to close the dropdown when clicked outside
in the capture fase, instead of in the bubbling fase.
Closes #166
=> Update ember-basic-dropdown to fix rendering issue in ember 2.2.0+

CHANGELOG.md, addon/components/power-select.js, addon/templates/components/power-select.hbs, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/single.hbs, tests/dummy/app/templates/docs/api-reference.hbs, tests/integration/components/power-select-test.js
This enables the component to be rendered already opened.
Example:
```hbs
{{#power-select options=opts selected=foo onchange=(action (mut foo)) opened=true as |opt|}}
{{opt}}
{{/power-select}}
```
Also, toggling the `opened` property on the context will open and close the component (identical behaviour as clicking on it).
Unlike all other properties passed to this component, `opened` is the only one designed to be mutable (otherwise it would diverge with the internal state of the component once it is opened normally, loosing it's usefulness).
The component is still not designed to be opened at the same time as other selects/dropdowns, so opening more than one component at the same time with this technique might cause unexpected results.
=> Enable open close via property

CHANGELOG.md, addon/components/power-select/multiple.js, addon/components/power-select/single.js, addon/templates/components/power-select.hbs, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/single.hbs, package.json, tests/dummy/app/controllers/legacy-demo.js, tests/dummy/app/templates/legacy-demo.hbs, tests/integration/components/power-select/custom-search-test.js, tests/integration/components/power-select/customization-with-compoments-test.js, tests/integration/components/power-select/disabled-test.js, tests/integration/components/power-select/ember-data-test.js, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/groups-test.js, tests/integration/components/power-select/keyboard-control-test.js, tests/integration/components/power-select/mouse-control-test.js, tests/integration/components/power-select/multiple-test.js, tests/integration/components/power-select/opened-property-test.js
Example: Open the select when focused.
```hbs
{{#power-select options=options selected=foo onchange=(action (mut foo)) onfocus=(action "didFocus") as |option|}}
{{option}}
{{/power-select}}
```
```js
actions: {
didFocus(select /*, e */) {
select.actions.open();
}
}
```
Closes #172 
This also updates `ember-basic-dropdown` to 0.7.0-beta.1, which changes the strategy to open the select from `onclick` to `onmousedown`. This was necessary for this feature but is also aligned with the way real selects works and makes the component feel much snappy :)
=> Onfocus action

CHANGELOG.md, addon/components/power-select/options.js, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/options.hbs, addon/templates/components/power-select/single.hbs
For the loading, no matches and search messages I just wrapped them in the previous `<ul` as it seems the most straightforward way to reuse styles.
Also, I'm setting `class="ember-power-select-options"` from the outer template. This helps to not break tests. I don't think it makes any difference to the passed in component.
=> let options component render the parent element

addon/components/power-select/options.js, addon/templates/components/power-select/multiple.hbs, addon/templates/components/power-select/multiple/selected.hbs, addon/templates/components/power-select/options.hbs, addon/templates/components/power-select/single.hbs
Add ARIA roles to dropdown menus.
In case you're wondering, in nested menus, `<li>` containing child submenu is still a `menuitem`: https://www.w3.org/WAI/GL/wiki/Using_ARIA_menus#Example_Code
=> Add ARIA roles

tests/dummy/app/templates/addons/index.hbs
Should be merged after the following is done:
- ember-power-select
- cibernox/ember-power-select-with-create#1
=> Add a link to ember-power-select-with-create

addon/components/power-select-multiple.js, addon/components/power-select.js, addon/utils/computed-fallback-if-undefined.js
This allows to forwards all attributes to `{{power-select-multiple}}` and be sure they will fallback to the default values when given undefined.
=> Make multiple select repect defalt values

addon/components/power-select.js, addon/templates/components/power-select-multiple.hbs, addon/templates/components/power-select.hbs, package.json, tests/dummy/app/templates/docs/api-reference.hbs, tests/dummy/app/templates/docs/the-list.hbs, tests/integration/components/power-select/general-behaviour-test.js
`dropdownPosition` is now `verticalPosition`. The old one still works but deprecated.
=> Update to basic-dropdown 0.8.0-beta.0

addon/components/power-select.js, addon/templates/components/power-select-multiple.hbs, addon/templates/components/power-select-multiple/trigger.hbs, addon/templates/components/power-select.hbs, addon/templates/components/power-select/trigger.hbs, tests/dummy/app/templates/components/selected-item-country.hbs, tests/dummy/app/templates/docs/api-reference.hbs, tests/dummy/app/templates/docs/the-trigger.hbs, tests/integration/components/power-select/customization-with-compoments-test.js
In the docs where it was showing you how to customize the trigger, it was really showing you how to customize the selected item. Updated the docs accordingly leaving you with nowhere demoing actually replacing the entire trigger.
I tested the changes with my previous app, remove the code I had hacked and it worked fine. 
I do not have anywhere currently I was using a multiple select and in the docs there was only a simple demo of multi select without any of the customization, so I believe I changed everything correctly to also apply with multi select, but please check them add. All the tests for multiple didn't include any customization since it's just the same as the single.
=> Added selectedItemComponent

CHANGELOG.md, addon/components/power-select-multiple/trigger.js, addon/templates/components/power-select.hbs, tests/dummy/app/templates/legacy-demo.hbs, tests/integration/components/power-select/multiple-test.js
When pressed backspace to delete the last option, the component would search `[object Object]`. Now it requires `searchField` and works as expected.
=> Fix Backspace on multiple select when options are objects

CHANGELOG.md, addon/components/power-select-multiple/trigger.js, addon/components/power-select.js, addon/components/power-select/before-options.js, tests/integration/components/power-select/multiple-test.js
Depending on the use case, the user might not want the search to be cleared (by examples
when building a typeahead component). Probably is a responsability of the component containing
the input deciding to clear or not when the component is cleared.
=> Don't automatically clear the search on close.

addon/components/power-select-multiple/trigger.js, addon/components/power-select.js, addon/templates/components/power-select.hbs, addon/templates/components/power-select/options.hbs, tests/integration/components/power-select/multiple-test.js
Since `ArrayProxy` is being deprecated (probably) this stops using it. This also helps tackle some unnecessary re-renders discovered and reported in #249
=> Stop using array proxy

CHANGELOG.md, addon/components/power-select-multiple/trigger.js, tests/integration/components/power-select/keyboard-control-test.js, tests/integration/components/power-select/multiple-test.js
=> BUGFIX Pressing ENTER when no option is highlighted doesn't invoke onchange

CHANGELOG.md, addon/components/power-select-multiple/trigger.js, addon/components/power-select.js, addon/templates/components/power-select-multiple/trigger.hbs, addon/templates/components/power-select.hbs, addon/templates/components/power-select/options.hbs, addon/templates/components/power-select/trigger.hbs, tests/dummy/app/controllers/legacy-demo.js, tests/dummy/app/templates/legacy-demo.hbs, tests/integration/components/power-select/custom-search-test.js
Until now, the `searchText` was updated as the user types, synchronously, even if the search was asynchronous.
This behaviour had 2 downsides:
* It might lead to bad results. Imagine this scenario:
```hbs
{{#power-select search=(action "asyncSearch") selected=selected as |user searchTerm|}}
{{highlight-substring user.fullName searchTerm}}
{{/power-select}}
```
If the user searchers for `ab` and waits, it will see results which the substring `ab` highlighted. However if now the user adds a "c" (resulting in `abc`) the text to be highlighted becomes `abc` immediately even if the search takes 300ms in update the results for those containing `abc`. During this time, it will try to highlight `abc` on results that don't contain that string.
Now, the `searchText` is named `lastSearchedText` and …
=> Ensure the second argument yielded to the block is updated simultaneously with the results

addon/components/power-select.js, addon/templates/components/power-select-multiple.hbs, addon/templates/components/power-select.hbs, app/styles/ember-power-select.scss, tests/dummy/app/templates/legacy-demo.hbs, tests/dummy/app/templates/public-pages/docs/api-reference.hbs
Disclaimer: It doesn't looks nice with the default styles.
=> Allow to pass `matchTriggerWidth=false` to let the dropdown grow with the content

addon/components/power-select.js, addon/components/power-select/before-options.js, addon/templates/components/power-select.hbs
Ember-basic-dropdown no longer call preventDefault on mousedown events
on the trigger. That means that the trigger will get the focus normally.
The beforeOptionsComponent used to docus the input inside when rendered.
The problem was that the trigger gets the focus after the component has
been rendered and steals the focus back.
With this change, the beforeOptionsComponent receives an event when the trigger
is focused, and can then safely set the focus to the input.
=> Completely control focus from within the beforeOptionsComponent

addon/components/power-select.js, tests/integration/components/power-select/custom-search-test.js
If options passed to the component, is a promise and search is enabled via `search=(action "search")` component do not return initial results, when term is empty.
```javascript
options: computed(function() {
return Ember.RSVP.Promise.resolve(function() {
return [{id: 1, text: 'demo'}, { id: 2, text: 'demo2' }];
});
});
```
It will work on initial search, but if you remove search term, it will show empty results.
=> Empty search, when term is empty and options is promise

CHANGELOG.md, addon/components/power-select-multiple.js, addon/components/power-select-multiple/trigger.js, addon/components/power-select.js, addon/templates/components/power-select-multiple.hbs, addon/templates/components/power-select-multiple/trigger.hbs, addon/templates/components/power-select.hbs, tests/dummy/app/templates/legacy-demo.hbs, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/multiple-test.js, tests/integration/components/power-select/public-actions-test.js
Now the search on multiple selects can be disabled. The trigger component only handles events
on it's content.
=> [FEATURE] Disable search in multiple selects

addon/components/power-select.js, addon/utils/group-utils.js, tests/dummy/app/templates/public-pages/docs/the-search.hbs, tests/unit/utils/group-utils-test.js
This will be the preferred option in the near future. It will allow to prioritize results when typing on the trigger instead of on the searchbox.
=> Allow the custom matchers to return numbers apart from booleans

addon/components/power-select.js
I would like to implement a selectOnTab property to allow the option to be selected when tabbed. It appeared I had to override the entire handleKeyDown action, but this was problematic based on the action keydown, if I did my code first, the action wouldn't fire.
It would be easier to just override the key I wanted to handle. To do this I split out the handling of each key into a method that could be overridden in an extended class.
This pull request does nothing but split the handling into those methods.
Once accepted I will follow up with a PR for implementing the selectOnTab. I did not include it in this request as I think this request would be useful to anyone extending the class and gives you the opportunity to not to take the selectOnTab functionally while still giving me the …
=> Seperated handleKeyDown into seperate overridable methods

addon/components/power-select.js, tests/integration/components/power-select/general-behaviour-test.js
`this.get('options')` could return a promise, so `_doSearch` is updated to handle it. Otherwise, `_doSearch` could be triggered and improperly excute `this.filter` on a promise, instead of a promises fulfilled value.
=> _doSearch should handle options as a promise.

app/styles/ember-power-select.scss
added css classes for `ember-power-select-multiple-option` and `ember-power-select-trigger-multiple-input` in RTL layout to align them to the right, as discussed in #331
=> Fix alignment of selected items in power-select-multiple for RTL layout

addon/components/power-select.js, addon/utils/group-utils.js, tests/dummy/app/controllers/public-pages/docs/the-search.js, tests/dummy/app/templates/public-pages/docs/the-search.hbs, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/multiple-test.js, tests/unit/utils/group-utils-test.js
That was soft-deprecated but now it emits a deprecation warning.
=> Deprecate returning a boolean from custom matchers.

ember-cli-build.js
This PR enables the babel polyfill through ember-cli-babel. This polyfill is needed to support several ES6 features listed here: https://github.com/babel/ember-cli-babel#features. Previously, the `for (let val of array)` statements in the tests/dummy/app were causing problems in IE 11 (ex: https://github.com/cibernox/ember-power-select/blob/master/tests/dummy/app/controllers/public-pages/cookbook.js#L30). With this fix the docs website works successfully in IE 11.
=> Enable babel polyfill

addon/components/power-select-multiple/trigger.js, tests/dummy/app/templates/public-pages/docs/multiple-selection.hbs
There is some kind of bug in IE that causes the input to gain the focus over and
over when it has placeholder.
This solution is less than ideal, but it's better to not have placeholder than
to have a select that you can't close.
=> Disabled placeholder of multiple selects in internet explorer 10 & 11

addon/templates/components/power-select/trigger.hbs
All text in the trigger is wrapped in some element except the yielded selected item. To allow for styling, wrapped this text in a span.
Did not opt for wrapping in the actual yield when ember-power-select is used, because that yield may also be used in options where is it already wrapped in an [LI element](https://github.com/cibernox/ember-power-select/blob/master/addon%2Ftemplates%2Fcomponents%2Fpower-select%2Foptions.hbs#L23)
=> Wrap yielded selected item in span

addon/components/power-select.js
In `power-select.js`, `concatenatedTriggerClasses` and `concatenatedDropdownClasses` didn't depend on `triggerClass` and `dropdownClass` correspondingly, which basically made it impossible to have dynamic values for those properties.
=> Fix concatenated class CPs

addon/components/power-select/options.js, addon/templates/components/power-select.hbs, addon/templates/components/power-select/options.hbs, test-support/helpers/ember-power-select.js, tests/acceptance/helpers-test.js, tests/dummy/app/controllers/helpers-testing.js, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/groups-test.js, tests/integration/components/power-select/mouse-control-test.js, tests/integration/components/power-select/multiple-test.js, tests/integration/components/power-select/public-actions-test.js
[NO MERGE] 
This allows to only add two events per dropdown, instead of 2 events per each element of the list.
In a heavy element with ~300 options render time goes from 250~300ms to something closer to 190~240.
This is preparation for adding touch devices.
Touch events would make render times linearly worse but with this approach they shouldn't have a performance penalty, and this should allow the component to not add `mouseover` event in devices without a mouse.
=> [BREAKING CHANGE] Use event delegation for a ~20% speed improvement

package.json, tests/dummy/app/templates/public-pages.hbs
This will cause every public page to start out scrolled to the top, and then when returning to an already visited route will return to the last remembered scroll position.
This makes moving forward and backward through the documentation pages feel nicer, because forward links scroll you to the top automatically, and backward links take you back to where you were when you clicked forward.
=> Improve docs pages scroll handling

CHANGELOG.md, addon/components/power-select.js, addon/templates/components/power-select-multiple.hbs, addon/templates/components/power-select.hbs, package.json, tests/dummy/app/templates/public-pages/docs/api-reference.hbs, tests/integration/components/power-select/opened-property-test.js
[REMOVE FEATURE] The opened property (the only using double bindings instead of DDAU) has been removed. It was the cause of some errors due to race conditions in the bindings propagation. It is still possible to pass `initiallyOpened=true` to render a select already opened, but it is a one time property. It won't onpen/close the select when mutated nor will be mutated when the select is opened or closed.
=> Remove `opened` feature

addon/components/power-select-multiple/trigger.js, tests/integration/components/power-select/ember-data-test.js
This fix issue #380 
With ember data, it's not possible to do `items.get('0')` to have the first value and it have to be converted to array. 
I can't do an integration test because [this line](https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select/ember-data-test.js#L20) gives an error because `server` is undefined.
=> Convert to array when it's possible

addon/components/power-select.js
Fixed deprecation warning for Ember 2.5.0.
See here -> https://github.com/emberjs/ember.js/pull/12303
=> fix deprecation warning for Ember 2.5.0

tests/dummy/app/templates/public-pages/docs/troubleshooting.hbs
updated troubleshooting guide to reflect the latest dropdownClass option, as `class='in-modal'` no longer solves this problem.
=> updated troubleshooting to use dropdownClass

CHANGELOG.md, app/styles/ember-power-select.scss, app/styles/ember-power-select/variables.scss, package.json, tests/dummy/app/styles/app.scss, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/multiple-test.js
When any element inside the select (in the trigger or in the content) has the focus (typically an input), the input itself is not focused. So style this kind of "active" state was impossible to style.
Now, selects that have **anything** inside focused have a `ember-basic-dropdown--focus-inside` class that can be target to customize styles.
By default, the trigger on this state will have the same styles as when it's focused.
A couple sass variables have been added to style this state.
This PR was made at 13K feet over the atlantic.
Closes #397
=> [ENHANCEMENT] Selects that have elements inside with focus have a special class to allow styling.

CHANGELOG.md, addon/components/power-select-multiple.js, addon/components/power-select.js, package.json, tests/integration/components/power-select/public-actions-test.js
Now the hooks are called just before open/close, giving the user the change to
prevent that from happening by calling `e.preventDefaul()` or returning `false`
Closes #445
=> [BUGFIX/BREAKING] `onopen`/`onclose` can prevent the select from open/close

addon/components/power-select-multiple.js, addon/components/power-select-multiple/trigger.js, addon/components/power-select.js, package.json, tests/integration/components/power-select/keyboard-control-test.js, tests/integration/components/power-select/public-actions-test.js
Before users could use `return false` or `preventDefault`. Now only `return false` works.
The reason for that is that some events need to be `defaultPrevented` to avoid browsers'
behaviour (like touchEvents to avoid trigger synthetic clicks), and sometimes preventing
the default behaviour of a event has consecuences we don't want (like preventing keydowns
make the input receiving the keydown to not update it's value).
For that, the idiomatic way now of preventing the default behavior is return false
from the `on*` actions.
=> [BREAKING] e.preventDefault no longer prevents the default component's behaviour

addon/components/power-select.js, package.json
Calls to didInitAttrs() in components has been deprecated in favor of init(): http://emberjs.com/deprecations/v2.x/#toc_ember-component-didinitattrs. Updated main power-select component to reflect the change.
=> Fix for didInitAttrs deprecation

addon/components/power-select-multiple/trigger.js, addon/templates/components/power-select-multiple/trigger.hbs, app/styles/ember-power-select.scss
This has been done by making the input a sibling of the options, inside the `<ul>`.
I'm not sure if this is an a11y no-no.
It might be. Check.
=> Avoid breakline in multiple selects

addon/templates/components/power-select.hbs
Use case is to trigger the focus handler when focusing the input in `ember-power-select-typeahead`.
PR to use it in that addon is https://github.com/cibernox/ember-power-select-typeahead/pull/10
=> Make focus handler available to custom triggers

test-support/helpers/ember-power-select.js, tests/acceptance/helpers-test.js, tests/dummy/app/templates/components/custom-trigger-with-search.hbs, tests/dummy/app/templates/helpers-testing.hbs
It will fallback to use any input[type=search] that it can find if the default
css classes are not there.
=> Improve selectSearch helper to be less dependent on css classes

addon/templates/components/power-select/options.hbs, tests/integration/components/power-select/general-behaviour-test.js
closes #479
- makes the loading message option consistent with other special option elements by adding the custom class `.ember-power-select-option--loading-message`
=> Add special class to loading message option

CHANGELOG.md, addon/components/power-select.js, tests/integration/components/power-select/custom-search-test.js
=> [BUGFIX] Custom matchers receive the entire option even when used along with searchField

CHANGELOG.md, addon/components/power-select.js, addon/components/power-select/options.js, tests/dummy/app/controllers/public-pages/docs/the-search.js, tests/dummy/app/templates/public-pages/docs/the-search.hbs, tests/helpers/start-app.js, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/keyboard-control-test.js, tests/integration/components/power-select/public-actions-test.js
That way highlight with the mouse doesn't trigger a scroll change, and
at the same time allows to scroll reliably using `didInsertElement` that
we have the guarantee that is called once the dom is ready.
This adds a nice new `scrollTo(option, dropdown, e)` action to the public API object received
by all the hooks of the component that can be used to command the select to scroll
to any option.
closes #488
=> [BUGFIX] Decouple scrolling from highlighting

CHANGELOG.md, addon/templates/components/power-select/options.hbs, addon/utils/group-utils.js, tests/integration/components/power-select/disabled-test.js
Although groups cannot be clicked it would be great if they could be marked as disabled using the aria-disabled tag. Then styling could be applied depending on if the aria-disabled tag is true or false.
=> Make it possible to disable groups

CHANGELOG.md, addon/components/power-select.js, addon/components/power-select/options.js, addon/utils/group-utils.js, app/styles/ember-power-select.scss, bower.json, tests/dummy/app/controllers/legacy-demo.js, tests/dummy/app/controllers/public-pages/docs/the-list.js, tests/dummy/app/templates/legacy-demo.hbs, tests/dummy/app/templates/public-pages/docs/the-list.hbs, tests/integration/components/power-select/disabled-test.js, tests/unit/utils/group-utils-test.js
Before this, options had to explicitly have `disabled: true` property to be
considered disabled. Since this changes, if any ancestor group is disabled,
the option is automatically considered disabled.
Also, styles have been improved a bit. Now disabled groups by default have the
disabled color, and the cursor is `not-allowed`. Options inside disabled groups
have the same styles than options with `disabled: true`
=> If a group is disabled, its options cannot be highligted or selected.

test-support/helpers/ember-power-select.js
Removes jscs warnings for anyone using a jscs linter such as `ember-suave`
=> Remove jscs warnings

tests/dummy/app/templates/public-pages/docs/api-reference.hbs
I had to dig into the code to find this parameter. Figured I'd add it to the reference.
=> DOCS - Add "searchMessage" parameter description to api-reference table

addon/components/power-select-multiple/trigger.js, addon/components/power-select/before-options.js, addon/templates/components/power-select-multiple/trigger.hbs, addon/templates/components/power-select/before-options.hbs, addon/utils/update-input-value.js
Now that the component is 2.3.1+, it can just use a regular `<input value={{}}`
and it will just work.
=> Use just regular inputs

addon/components/power-select-multiple/trigger.js
=> Fix IE check on FastBoot

package.json, tests/integration/components/power-select/disabled-test.js
Hey @cibernox.
Disable state is not working properly if it depends of some property.
Here is reproducing of this bug
P.S. Sorry for messing in docs. I will remove it, just reproducing this bug.
=> [BUG] Multi-select disable state

addon/components/power-select.js, addon/components/power-select/search-message.js, addon/templates/components/power-select.hbs, addon/templates/components/power-select/search-message.hbs, app/components/power-select/search-message.js, tests/dummy/app/templates/components/custom-search-message.hbs, tests/dummy/app/templates/public-pages/docs/architecture.hbs, tests/integration/components/power-select/customization-with-compoments-test.js
Adds `noMatchesMessageComponent` and `searchMessageComponent` options to customize the no-matches and search message components respectively.
=> Allow customizing the search message component

addon/components/power-select.js, addon/components/power-select/before-options.js, package.json, tests/integration/components/power-select/a11y-test.js, tests/integration/components/power-select/public-actions-test.js
Following https://github.com/cibernox/ember-basic-dropdown/pull/120, this also makes the public API of this component an immutable object that gets replaced whenever the state of the component changes.
This will allow to get rid of observers in sub-components and replace them with `didReceiveAttrs`.
This can also enable fancy things like time-travel debugging, although for that to be fully reliable I'd need to move more properties that right now are internal into the public API, even if they are underscored.
=> Immutable api

package.json
This fixes a problem where more than one component with renderInPlace=true
rendered at the same time caused an exception.
Closes #606
=> Update EBD to 0.13.0-beta.2

index.js
In an engine, the addon errors because `app.options` is `undefined`. This PR guards against this by checking if `app.options` is an object.
=> Check if app.options is available

CHANGELOG.md, addon/components/power-select.js
=> [BUGFIX] Ensure scrollTo targets the proper list of options if another select is being animated out

tests/dummy/app/components/animated-options.js, tests/dummy/app/templates/components/animated-options.hbs
Updating the customized `optionsComponent` in the demo so that keyboard navigation works again.
=> Fix keyboard navigation in the navigable-select demo

package.json, tests/dummy/app/components/animated-options.js, tests/dummy/app/components/navigable-select.js, tests/dummy/app/templates/components/animated-options.hbs
This switches from liquid-bind's `use=` to `rules=` so we can do declarative matching.
Also, both the existing code and my new version rely on equality checking that was not working with the latest code in power-select due to `toArray` on `options`. I patched the demo so that toArray is a no-op on our demo data, but it would be nice to skip the unnecessary copy in cases where options is already a true Array.
This PR builds off #678.
=> Improved animation

CHANGELOG.md, tests/dummy/app/templates/public-pages/cookbook/css-animations.hbs
The examples in the docs already use `animation` and not `transition`, but this PR
add an explicit comment explaining that CSS transitions are not supported
Closes #694
=> Document that automatic animation detection doesn't work with CSS transitions

CHANGELOG.md, test-support/helpers/ember-power-select.js, tests/acceptance/helpers-test.js, tests/dummy/app/templates/public-pages/docs/test-helpers.hbs
This allows to select options in a group that have the same text than
some other option in another group. Before, passing just the content,
only the first matching option could be reached. Now using CSS selectors,
any option can be selected.
Closes #691
=> Allow `selectChoose` to receive a CSS selector as second argument

CHANGELOG.md, test-support/helpers/ember-power-select.js, tests/acceptance/helpers-test.js
Example errors:
```
- You called `selectChoose('.cities', 'Rome')` but no power-select was found using selector `.cities`
- You called `selectChoose('.cities', 'Rome')` but "Rome" did not match any option
```
Closes #698
=> `selectChoose` and `selectSearch` throw explicative errors when something goes wrong

addon/components/power-select.js, package.json, tests/integration/components/power-select/custom-search-test.js
With ember-concurrency gaining popularity every day and cancellable promises
around the corner (sic) it's time to start being good citizens and cancel all
work that can be cancelled when the component is no longer interested in it.
There is a couple situations where this can happen:
If the `search` action returns a `thenable` object that responds to the
`.cancel()` method, firing another search before the first one is completed will
cancel the previous. This was possible before by just adding `.restartable()`
to your e-c task, but now it will work with any cancellable object.
Another situation where this could happen is when, after firing a search that
returns can cancellable-thenable, and before that search completes, the searchbox
gets cleared. In EPS, clearing the search doesn't fire …
=> Add support for cancellables

CHANGELOG.md, addon/components/power-select.js, addon/templates/components/power-select-multiple.hbs, addon/utils/group-utils.js, tests/dummy/app/controllers/legacy-demo.js, tests/dummy/app/templates/legacy-demo.hbs, tests/dummy/app/templates/public-pages/docs/api-reference.hbs, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/multiple-test.js
By default when a select component opens, the highlighted element is the selected one,
or the first option in the list if nothing is selected. This is the right behaviour for
99% percent of the cases.
However, there might be some situations where the user wants to customize this, and now
it's possible passing `defaultHighlighted=something`.
That `something` can be either one of the options, or a function that takes the publicAPI
of the component and returns one of the options.
=> [FEATURE] Allow to customize what element is highlighted by default

tests/dummy/app/templates/public-pages/docs/api-reference.hbs
for consistency with how that data type is listed for all the other API options
=> lowercase string data type in api-reference.md

test-support/helpers/ember-power-select.js
Tests which use the `clickTrigger` helper fail in IE11.
=> Fix error constructing Event in Internet Explorer 11

CHANGELOG.md, addon/helpers/ember-power-select-is-group.js, addon/templates/components/power-select/options.hbs, app/helpers/ember-power-select-is-group.js, tests/integration/components/power-select/groups-test.js
That an option has `groupName` is not enough to make it a group, it
also has to have an options property. Created a template helper that
runs the same logic present in the `isGroup` utility function in /utils
=> Better check for groups.

package.json
Since you use ES6 in node-land since #776 this should be reflected in `package.json`
=> Update node version in package.json

index.js
Although using `_lookupApp()` worked, it wasn't a fool-proof way of finding the correct parent App and I feared breaking other peoples' builds in future EmberCLI versions:
We are backporting `findHost()` method if you're running EmberCLI < 2.7 and using it if you're on a version > 2.7.
=> Find parent app by using findHost method

tests/dummy/app/templates/public-pages/docs/api-reference.hbs
**EDIT**
This PR now documents the use of `buildSelection` and reorders the API reference. I'm happy to circle back later and create an example of this, but for now need to return to some other work.
Will open a follow-up issue to do so once this is merged.
<hr />
Closes #822.
Just an initial PR in the event that we want to allow unselection via a configuration option. Obviously open to any kind of feedback and understand that, if approved, will require some documentation.
=> Allow unselection in select fn

addon/templates/components/power-select-multiple/trigger.hbs, tests/integration/components/power-select/multiple-test.js
I added behavior to `templates/components/power-select-multiple/trigger.hbs` so that the remove-button is hidden if an option is disabled. In our app this happens within the following use case: 
There are options which are only addable by an admin. The regular user should see the options but should not be able to remove them. 
In our UI this looks something like this:
The green category are the "admin categories". They should not be deletable by the regular user. Therefore the disabled flag is set on them.
@cibernox let me know what you think. Would be great to have a way to "disable" single options. Maybe my solution is sufficient 😉
=> Disable trigger when option is disabled

package.json, tests/integration/components/power-select/assertions-and-deprecations-test.js, yarn.lock
Recent changes between 2.11.2 and 2.11.3 caused the test suite to fail.
IMHO this is a breaking change and a bug in ember, but in the meanwhile I'm
going to comment the failing test.
=> Fix tests in 2.11.3+

addon/templates/components/power-select-multiple.hbs
We reopen `power-select` so we can add some attribute bindings for test hooks. This requires all instances to not be tagless, so we need the `tagName` property we pass to `power-select-multiple` to trickle down to `power-select`.
=> Add `tagName` to arguments passed from `power-select-multiple` to `power-select`.

CHANGELOG.md, test-support/helpers/ember-power-select.js, tests/integration/components/power-select/helpers-test.js
Identical to the acceptance one. Eventually will replace it.
TODO: Other acceptance helpers should be exposed too.
If there is a single select in the integration test, you can pass
an empty string as selector: `selectChoose('', 'three')`. Perhaps
I should check the arity and allow a shorter `selectChoose('three')`
/cc @martndemus It turned to be as easy as I thought it was.
=> [ENHANCEMENT] Expose a `selectChoose` integration helper

addon/components/power-select.js
Preserves the raw results returned from the search handler by setting it on the `publicAPI`.
**Use Case:** We extend ember-power-select to render a "Load more" button in the `afterOptionsComponent`, and all of our models are special `ArrayProxy`'s that are pagination aware and have self-contained `loadMore()` functions. This is working great so far, but there's no way to access the ArrayProxy we return from a search from inside ember-power-select, since the call to `toPlainArray` effectively destroys our ArrayProxy.
We've got it working by overloading `handleAsyncSearchTask` with this exact change, but this might be a positive change for others looking to implement a similar solution.
=> Preserve rawSearchResults

tests/dummy/app/templates/public-pages/docs/api-reference.hbs
To http://www.ember-power-select.com/docs/api-reference.
Not a lot of thought went into this, so feel free to close if this is the wrong thing to do or I'm wrong about something! Just noticed `isOpen` in my console, didn't see it in the docs, and figured it'd be fastest to open a PR.
Thanks so much for the addon :) its beauty brings me much joy.
=> Add isOpen to the API reference docs

addon/components/power-select.js, tests/integration/components/power-select/keyboard-control-test.js
If we do not ignore them, we end up, for instance, filtering by "r" when when we
press ctrl+r to reload the page, or filtering by "l" when doing ctrl+l to select
the browser's URL.
It is always a bit annoying to witness this involuntary filtering, but more so
when the widget auto-saves its content. Especially so with ctrl+r, with which
you might not even notice the change because of the page reload.
=> Ignore keydown with modifier keys pressed

addon-test-support/helpers.js
If the trigger is scrolled off screen, the options menu may not appear properly, causing the action not to fire. This commit changes the test helpers to scroll the trigger into view (assuming the browser supports the function) before trying to open the menu and select an item.
=> selectChoose, selectSearch scrollIntoView

addon/components/power-select.js, tests/integration/components/constants.js, tests/integration/components/power-select/keyboard-control-test.js
This PR adds the ability for users to select an option by typing from their Numpad keys.
In order to achieve this I expanded the whitelist of allowed keycodes that trigger the `triggerTypingTask` task so as to include the appropriate keycodes. I also had to update the code which converted the keycode into an actual character so as to take this into account since the keycode for Numpad keys does not directly translate to the unicode representation of the equivalent number character. 
Docs:
- info on Numpad keys in Javascript [here](https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes)
- info on String.fromCharCode [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode)
=> Feature - Add support for Numpad typing

addon/components/power-select.js, tests/integration/components/power-select/keyboard-control-test.js
Replaces #965 
@BenjaminHorn It turns out there was no error. The problem is that when your options are not strings, Ember Power Select needs to know what field it should filter by, using `seachField="name"`. Since you didn't provide any, options were coherced to `[object Object]`, that is why `c` and `o` and `b` and `j` and `t` matched.
I've added a dev-time assertion that will be stripped in production builds to help users when they forget about `searchField`.
=> Raise helpful assertion

addon/templates/components/power-select.hbs, app/styles/ember-power-select.less, app/styles/ember-power-select.scss, tests/dummy/app/styles/components/docs.scss, tests/integration/components/power-select/customization-with-attrs-test.js, vendor/ember-power-select-bootstrap.css, vendor/ember-power-select-material.css, vendor/ember-power-select.css
`classNames` being passed forward allows direct configuration of `{{basic-dropdown}}` which matters for `renderInPlace=true` as you may need to distinguish in CSS between an `.ember-power-select` and your own custom `.ember-basic-dropdown` on the same page.
=> Delete residual CSS from tagName removal. Allow classNames propagation.

addon/templates/components/power-select.hbs, tests/dummy/app/templates/components/custom-before-options.hbs, tests/integration/components/power-select/customization-with-components-test.js
This allows behavior like having the placeholder serve as a header for the select when open.
=> Expose placeholder to beforeOptionsComponent.

.gitignore, .travis.yml, config/ember-try.js, ember-cli-build.js, package.json, testem.js, tests/.eslintrc.js, tests/dummy/app/app.js, tests/dummy/app/index.html, tests/dummy/config/environment.js, tests/dummy/config/targets.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, yarn.lock
Bump ember-cli, ember, and ember-truth-helpers.
The mostly cosmetic differences are from `ember init`, should be cleaner going forward.
ember-truth-helpers had a 2.0 release recently which bumped it to the new modules format. As this library has a dependency, we need to update here. The semver breaking change in the 2.0 release is that ember-truth-helpers no longer supports Node < 4 or Ember < 2.0. Changelog: https://github.com/jmurphyau/ember-truth-helpers/releases/tag/v2.0.0
ember-power-select already does not support Node < 4 b/c of its dependency on ember-cli-babel 6.6.0. If ember-power-select currently supports only Ember >= 2.0 then I do not suggest a major version bump. If it does support legacy Ember, this patch requires a major version bump dropping support.
Edit: I had to add a …
=> Bump ember-cli, ember, ember-truth-helpers

addon/templates/components/power-select.hbs, package.json, tests/dummy/app/templates/public-pages/docs/api-reference.hbs, tests/integration/components/power-select/a11y-test.js, yarn.lock
Part of fix for https://github.com/cibernox/ember-power-select-typeahead/issues/67
in `ember-power-select-typeahead`
=> Allow `triggerRole` to be set

addon/components/power-select.js
I opened a similar PR while back, but declined when I couldn't consistently reproduce the issue. Now I can, although the setup is hard to explain. The specific error I get is `TypeError: Cannot read property 'isOpen' of undefined`, which happens on line 540 (`publicAPI.isOpen`).
I have a page with two ember-power-selects. When the first is selected, it populates the choices of the second (from a `hasMany` association from the selected model). When ember tears down all the models at the end of an acceptance test, it triggers the change event on the `hasMany` relationship, causing ember-power-select to want to update, but since everything is mid-teardown I get the error I mentioned. There's a lot of other stuff going on in my test, but I think it boils down to a race condition that this PR …
=> Bail out of _updateOptionsAndResults if `isDestroying`

test-support/helpers/ember-power-select.js, tests/dummy/app/templates/public-pages/docs/test-helpers.hbs, tests/dummy/app/templates/snippets/test-helpers-1-js.js, tests/helpers/start-app.js, tests/integration/components/power-select/a11y-test.js, tests/integration/components/power-select/custom-search-test.js, tests/integration/components/power-select/customization-with-components-test.js, tests/integration/components/power-select/disabled-test.js, tests/integration/components/power-select/ember-data-test.js, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/groups-test.js, tests/integration/components/power-select/helpers-test.js, tests/integration/components/power-select/keyboard-control-test.js, tests/integration/components/power-select/mouse-control-test.js, tests/integration/components/power-select/multiple-test.js, tests/integration/components/power-select/public-actions-test.js, tests/integration/components/power-select/touch-control-test.js, tests/integration/helpers-test.js
The helpers exported from there will continue to work for a while, but the amount of deprecation will be so annoying that people will upgrade quicky.
=> Deprecate /test-support folder

addon/components/power-select.js, addon/utils/computed-options-matcher.js, addon/utils/group-utils.js, tests/dummy/app/templates/public-pages/docs/api-reference.hbs, tests/integration/components/constants.js, tests/integration/components/power-select/disabled-test.js, tests/integration/components/power-select/keyboard-control-test.js, tests/integration/components/power-select/type-ahead-test.js, tests/unit/utils/group-utils-test.js
**NOTE** For this behaviour to work when the select is open, the user
needs to disable the search.
About this PR
======
This PR aims to give EPS a native-like behaviour.
What's the UX in current browsers?
======
For this, we compared safari, chrome, and firefox. Both safari and
chrome have different behaviours depending on whether the select is
open or closed. Firefox does not. We believe the select should behave
the same in both states, and a deeper look at blink's code seem to proof
it. For the purposes of this PR, the behaviour explained and implemented
is the one reproducible when the select is closed in safari and chrome
(firefox only implement such behaviour).
When a user focuses on a select, does not matter the state, they can
go to the next option that matches the treated input. …
=> Enable native-like search logic

tests/integration/components/power-select/customization-with-components-test.js, tests/integration/components/power-select/disabled-test.js, tests/integration/components/power-select/general-behaviour-test.js, tests/integration/components/power-select/keyboard-control-test.js, tests/integration/components/power-select/multiple-test.js, tests/integration/components/power-select/public-actions-test.js, tests/integration/components/power-select/type-ahead-test.js
This PR replaces the calls to DOM methods `.focus()` and `.blur()` in tests
with helpers from `ember-native-dom-helpers`.
The corresponding `run` wrappers have also been removed.
=> Prefer ember-native-dom-helpers helpers in tests

addon/templates/components/power-select.hbs
Make `selectedItemComponent` available in `beforeOptionsComponent`. This will allow for a persistent header showing the overall selected items inside of `power-select-multiple`. This matters in the case where the list ends up scrolling.
=> selectedItemComponent into beforeOptionsComponent

addon/components/power-select.js
This fixes #1094 
I just used the `get` function here, although i suspect there's probably a more elegant way to see if an object is `then-able`. 
I'm not sure how to write a test for this, but my fix doesn't break any existing tests and It Works On My Machine (and in my app) (TM).
=> fixes nested native getter

ember-cli-build.js, package.json, tests/dummy/public/_redirects, yarn.lock
This PR enables Fastboot pre-rendering of the entire docs site using [prember[(https://github.com/ef4/prember). For URL discovery, it's using the newly-published [prember-crawler](https://github.com/ef4/prember-crawler)
I tested the `_redirects` on netlify to confirm it will work, and it does. By default, prember outputs an `_empty.html` file that contains your original (empty) index.html content, since your pre-rendered index.html file will have actual content in it.
=> Pre-render docs site at build time

addon-test-support/index.js, package.json, yarn.lock
Fixes https://github.com/cibernox/ember-power-select/issues/1095
Following up with https://github.com/cibernox/ember-power-select/commit/d696c282ecb922b82e49d60ad246bd6439652af8, this PR removes the last references to ember-native-dom-helpers in the codebase.
The build fails, but only for the same reasons that master is failing currently.
=> Remove native dom helpers

addon/templates/components/power-select-multiple/trigger.hbs, tests/dummy/app/templates/components/selected-country.hbs, tests/dummy/app/templates/components/selected-item-country.hbs, tests/integration/components/power-select/customization-with-components-test.js
Fixes #1074
Also added a few missing tests that I noticed were needed
<hr>
**NEW PR**: Originally https://github.com/cibernox/ember-power-select/pull/1075
=> Add extra params for `selectedItemComponent` on trigger (power-select-multiple)

addon-test-support/index.js
Remove a console.log, which clutters the test output. See #1114 .
=> Remove console.log from test helper

addon/components/power-select.js
In Ember 3.2, a new assertion was added that prevents sending actions to objects that are already destroyed.
`ember-power-select` does this specifically with the `deactivate` action, and in our Ember 3.2 app this causing test failures because these actions are being sent after the component itself has been cleaned up.
Here are some examples of where this issue has come up elsewhere:
- https://github.com/emberjs/ember.js/issues/16820
- https://github.com/emberjs/ember.js/issues/16778
This PR prevents this error by wrapping calls to `deactivate` in `if (!this.isDestroying)`.
=> guard against destroying hook when calling deactivate

addon/templates/components/power-select.hbs, tests/dummy/app/templates/public-pages/docs/api-reference.hbs
Need to pass in `animationEnabled` property through ember-power-select, so that it can be used by ember-basic-dropdown.
Been running into ember run loop errors related to animating dropdown when the component has already been destroyed, as it's scheduled afterRender here - https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L183
Had submitted a similar PR for this property to be passed in through ember-power-select-typeahead, which has been merged recently. 
https://github.com/cibernox/ember-power-select-typeahead/pull/77
=> Add animationEnabled to be passed down to ember-basic-dropdown

addon/components/power-select.js, addon/components/power-select/options.js, addon/templates/components/power-select.hbs, tests/dummy/app/templates/public-pages/docs/api-reference.hbs, tests/integration/components/power-select/mouse-control-test.js
When false, will disable automatically highlighting an option
when hovered over with the mouse. This will prevent unintentionally
selecting a new value when tabbing through a form with an EPS field
while the user's mouse is where the list will appear when the EPS
gains focus, it is set to automatically open onFocus, and then closes 
when it loses focus.
=> Add highlightOnHoverEnabled to be used in options.js

tests/dummy/app/templates/public-pages/cookbook/css-animations.hbs
'clone' is the intended word in the context, and the spelling error 'close' may cause some confusion to the reader
=> close -> clone

addon-test-support/index.js, package.json, yarn.lock
In EBD 1.0.5 a fix for better a11y was introduced. It makes aria-owns to only be present on the trigger when the dropdown is open. Test helpers in EPS relied in that property being there all the time, but now
they work both ways.
=> [BUGFIX] Allow test helpers to work with EBD >=1.0.5

addon/components/power-select.js
~We should only prevent the scroll when the target is the body. I have an issue that my target is an input field with a custom `triggerComponent`. The `e.preventDefault()` is preventing me from typing in a space 😅~
We should not handle the spacebar if the node is a `textarea` or an `input` field. I have an issue when my target is an input field with a custom `triggerComponent`. 
**Before:**
**After:**
=> Prevent scroll only if target is body

package.json, yarn.lock
I was getting a weird error related to ember-concurrency in a fresh octane blueprint app.
```
Uncaught (in promise) TypeError: Found non-callable @@iterator
at new ComputedProperty (metal.js:2766)
at new TaskProperty (-task-property.js:398)
at task (index.js:58)
at Module.callback (power-select.js:447)
at Module.exports (loader.js:106)
at Module._reify (loader.js:143)
at Module.reify (loader.js:130)
at Module.exports (loader.js:104)
at requireModule (loader.js:27)
at Class._extractDefaultExport (index.js:422)
```
So I updated ember-concurrency to 0.9.0 and now it works 
helps #1204
=> bump ember-concurrency

package.json, yarn.lock
This PR allows both ember-concurrency@0.8.x as well as @0.9.x.
Fixes #1219
=> Allow ember-concurrency 0.8.x & 0.9.x

addon/templates/components/power-select-multiple.hbs, addon/templates/components/power-select.hbs
I believe these arguments should have `@` prepended. Please confirm.
=> Prepend missing @ to arguments

blueprints/ember-power-select/index.js
The feature has been disabled in Ember.js, so it can be safely removed now.
=> Remove experimental MU blueprint

addon/components/power-select/before-options.js
This was the only usage of `this._super` in a native class. A last occurence is remaining in the tests but in an Object: `Component.extend({})`.
As explained [here](https://blog.emberjs.com/2019/01/26/emberjs-native-class-update-2019-edition.html), native `super` should be used over `this._super` in native classes.
=> typo: Remove this._super to use native super

package.json, yarn.lock
https://github.com/cibernox/ember-power-select/pull/1276 would have been caught by the recently added [no-ember-super-in-es-classes rule](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-ember-super-in-es-classes.md)
@cibernox is there any reason why you don't use something like dependabot? If you'd like I could open a PR to add the config (which I think would turn it on).
Thank you for the great work on this addon!
=> Bump eslint-plugin-ember to v7

addon/components/power-select.js
This assertion was somehow lost during the update to glimmer components
=> Assert that every select has an `@onChange` function

CHANGELOG.md, package.json
This PR addresses one part of the issue #1296.
Note. When I ran `yarn install`, the `yarn.lock` file remained unchanged.
=> Moved ember-assign-helper from devDependencies to dependencies in package.json

tests/dummy/app/templates/public-pages/docs/styles.hbs, tests/dummy/app/templates/snippets/skip-styles-config-js.js
I'm working on an addon that will wrap ember-power-select and provide its own styles using tailwind plugins. In that respect, I won't be using sass nor less, and I don't want the pre-compiled CSS.
=> Document how to skip styles

addon/templates/components/power-select.hbs
`@animationEnabled` was being incorrectly passed to `<BeforeOptions>` component. It should be passed in to the `<dropdown.Content>` component.
=> fix @animationEnabled argument

addon/components/power-select.js, addon/components/power-select/no-matches-message.js, addon/templates/components/power-select.hbs, addon/templates/components/power-select/no-matches-message.hbs, app/components/power-select/no-matches-message.js, tests/dummy/app/templates/public-pages/docs/architecture.hbs, tests/integration/components/power-select/customization-with-components-test.js
This applies the same treatment of the `searchMessageComponent` to the no matches message.
This could prove useful to build more complex interactions when a search text is not found (e.g create a new item with the search text?).
=> add no matches message component

addon/templates/components/power-select.hbs, tests/integration/components/power-select/customization-with-components-test.js
on #1311 I messed up because `this._triggerTagName` was already being used on the power select trigger, so setting that property meant setting both properties, which might not be desired.
To make this clearer, I prefixed the private ebd related properties with `ebd`.
=> pass in triggerComponent and contentComponent

addon/templates/components/power-select-multiple/trigger.hbs, addon/templates/components/power-select/before-options.hbs, tests/dummy/app/templates/components/custom-trigger-with-search.hbs
together with: @krainboltgreene
ensures that `spellcheck` is set to "false"
=> wrap spellcheck boolean in curlies

addon/templates/components/power-select.hbs
It fixes the issue #1352 (missing `@select` after code refactoring).
=> #1352 Expose PublicAPI to AfterOptionsComponent

addon/components/power-select.ts, tests/integration/components/power-select/custom-search-test.js
This is a regression from previous versions of power-select
=> When using a synchronous custom search function, the first result does not get highlighted

package-lock.json, package.json
After upgrading my apps to ember 3.20, deprecation warnings began appearing due to the use of `setSourceDestroying`.  It seems these were stemming from dependencies of `@glimmer/component` lower than version 1.0.1 (the deprecation warnings were addressed in that [version](https://github.com/glimmerjs/glimmer.js/releases/tag/v1.0.1)).
Upgrading the `@glimmer/component` version here, as well as `ember-basic-dropdown` (who updated `@glimmer/component` [recently](https://github.com/cibernox/ember-basic-dropdown/pull/571)) should remove these deprecations in apps using ember 3.20.
=> Upgrade @glimmer/component to avoid deprecations with ember 3.20

addon/components/power-select.ts, tests/integration/components/power-select/general-behaviour-test.js
PowerSelect Component instances accumulate in the JS Heap when the initial `selected` value is a PromiseProxy. That's because we [addObserver for PromiseProxies](https://github.com/cibernox/ember-power-select/blob/fb688e44c166e42e58d6c89de02ede553464e38a/addon/components/power-select.ts#L335-L341), but the observer is not removed prior to component teardown.
We now remove the observer on component teardown, which allows PowerSelect Component instances to be removed from the JS Heap when the Component is destroyed.
Fixes #1391
---
The initial state of the JS Heap contains **1** PowerSelect instance, and the final state contains **1** instances (even though we visited a page containing the PowerSelect with `selected` PromiseProxy a total of five times). When the component is destroyed, it …
=> [bugfix] remove remaining observer on PowerSelect teardown

addon/components/power-select/options.hbs, addon/components/power-select/options.ts
An extra `PowerSelect` Component instance remains in the JS Heap until the `PowerSelect/Options` Component is re-rendered. That's because we [addEventListeners in PowerSelect/Options](https://github.com/cibernox/ember-power-select/blob/fb688e44c166e42e58d6c89de02ede553464e38a/addon/components/power-select/options.ts#L57-L72) but the listeners are not removed prior to component teardown.
This PR eagerly removes all event listeners on component teardown, which allows PowerSelect Component instances to be removed from the JS Heap when the Component is destroyed.  This implementation may attempt to remove listeners that have not been added. This is okay since calling removeEventListener() with arguments that do not identify any currently registered EventListener on the EventTarget has no …
=> [bugfix] Remove event listeners on destroy

.travis.yml, config/ember-try.js, package.json
We've just released ember-concurrency 2.0.0-beta.1. It's a largely API-compatible re-engineering of ember-concurrency's internals to support tracked properties and decouple from Ember (shedding EmberObject, etc.). As a popular library which depends on ember-concurrency, it would be nice for `ember-power-select` to support both 1.x and 2.x versions concurrently so that folks can upgrade the version of ember-concurrency in their applications at their leisure without waiting for all the add-ons they use to switch over to a newer version (and risk leaving folks who cannot upgrade yet behind.)
This PR adds some scenarios to ember-try to enable testing against both major releases and relaxes the version restriction.
=> Support both ember-concurrency 1.x and 2.x

addon-test-support/helpers.js, addon-test-support/index.js, tests/integration/components/power-select/helpers-test.js
**summary:**
- Adding new test helper `getDropdownItems`.
- `getDropdownItems` will return all the displayed items in the `power-select` dropdown
- Using this test helper to assert the displayed drop down items.
=> Adding getDropdownItems test helper to ease testing

addon/components/power-select/options.hbs, package-lock.json, tests/integration/components/power-select/a11y-test.js
Hola Miguel @cibernox! 🎉
My team is currently working through a VPAT accessibility audit. One of the most pressing blockers surfaced is that highlighted select options are not spoken by any of the screen readers - Major (VoiceOver, NVDA, JAWS) or Minor (ChromeVox, etc).
This PR enables screen readers to announce highlighted select options by alerting screen readers to highlighted select options. 
_VoiceOver Demo_
https://youtu.be/n2qYc0gI5i0
https://deploy-preview-1409--rubber-tapper-eddies-44787.netlify.app/
Just want to say Thanks for all the hard work leading `ember-power-select`, I know it isn't easy!
=> Enables screen readers to announce highlighted select options.

package.json
Now that we use glimmer components this dependency is no longer needed. There is still one usage in the dummy app though, so we can move it to `devDependencies` for now.
=> package.json: Move `@ember-decorators/component` into `devDependencies`

package.json
same as https://github.com/cibernox/ember-basic-dropdown/pull/584
This avoids users having to use resolutions to update to ember-truth-helpers v3 :)
=> Widen `ember-truth-helpers` dependency constraint to allow v3.x

addon/components/power-select.hbs, tests/integration/components/power-select/opened-property-test.js
#1288 Seems to have introduced a bug whereby providing `@initiallyOpened` AND `@selected` causes an error as described in #1426 .
This PR adds a failing test for the bug and also the bug fix.
Closes #1426
=> 🐞 Fix error when providing `@initiallyOpened={{true}}` and `@selected`

addon/components/power-select-multiple.hbs, addon/components/power-select.hbs
Sometimes reaching the core is needed, this was previously supported not sure when it got deprecated or regressed, i think when jumping from 3.0.6 to 4.x.x
`ember-paper` depends on it:
https://github.com/miguelcobain/ember-paper/blob/1c23f2ef65ffd3f496aab1ac1cc1ed88b3a5729f/addon/components/paper-select/template.hbs#L18
Previously:
https://github.com/cibernox/ember-power-select/blob/672ad84e7a96c4fdc8f1aff42b4c77be669e8156/addon/templates/components/power-select.hbs#L14
=> add back customizing ember basic dropdown trigger and content components

addon/components/power-select.ts
It seems there's a chance that the observer doesn't exist on willDestroy, if the component starts destroying before the observer gets added in the .then here 
https://github.com/cibernox/ember-power-select/blob/c4d595617d7301c9c62021cd1945ed6b809facac/addon/components/power-select.ts#L352
Not sure how else this could be guarded, because we don't have the check  `Object.hasObserverFor('content')`, we could add a stateless flag though
=> guard removing observer

addon/components/power-select.ts, tests/integration/components/power-select/keyboard-control-test.js
Fixes #1400 
This resolves 2 keyboard navigation issues with power-select-multiple that I've run into
1.  Issue #1400: pressing Enter on an item that was just selected adds an array of all previously selected items to the `selected` array
2.  Keyboard navigation in the list of options does not resume after an option is selected via Enter keydown. It is reset to the beginning of the list
=> Fix arrays appended to multiple select's selected array

addon/components/power-select/options.ts, tests/integration/components/power-select/mouse-control-test.js
This change ensures that when an option in the `PowerSelect/Options` component is clicked, the action registered on `mouseup` will pass the`mouseup` `Event` all the way to the `onChoose` action.
Previously, the second AND third event passed to the onChoose action was the dropdown, aka `this.storedAPI`, due to arguments not being passed as expected from the `mouseup` handler, and the Event was never received by the `onChoose` action.
A test has been included in this change. 
Fixes #1412
=> onChange action receives Event as last arg on mouseup

addon-test-support/index.js, addon/components/power-select.hbs, addon/components/power-select.ts, addon/components/power-select/before-options.hbs, addon/components/power-select/options.hbs, addon/utils/group-utils.ts, tests/integration/components/power-select/a11y-test.js, tests/integration/components/power-select/mouse-control-test.js, tests/unit/utils/group-utils-test.js
The current implementation doesn't appear to work well with screen readers. Specifically, screen readers are unable to recognize and read out the options because of missing aria attributes.
This PR fixes a few issues from the previous checklist created by someone else "[a11y] Refine ARIA implementation": https://github.com/cibernox/ember-power-select/issues/806
It closes these two issues from that list:
- Implement aria-activedescendant on the combobox. This property allows focus to stay on the trigger but tells the screen reader which option in the listbox is currently highlighted.
- Remove aria-controls from ul elements inside the listbox. (This relationship was backwards. The trigger controls the options list, not the other way around.)
I also compared ember-power-select to the …
=> Improve ember-power-select screen reader accessibility

addon/components/power-select.hbs, tests/integration/components/power-select/a11y-test.js
The `aria-activedescendant` property should always refer to a valid element. When the dropdown is closed, none of the options are in the DOM, so `aria-activedescendant` should be blank.
=> aria-activedescendant property should not be present when dropdown is closed

addon/components/power-select-multiple/trigger.hbs, addon/components/power-select.hbs, tests/integration/components/power-select/a11y-test.js
Because `<PowerSelectMultiple>` uses `<PowerSelect>` I naively assumed that I didn't need to do anything with `<PowerSelectMultiple>` when I did the accessibility improvements in https://github.com/cibernox/ember-power-select/pull/1481. Of course that's not the case.
I followed the W3C WAI-ARIA 1.2 recommendation for comboboxes:
https://www.w3.org/TR/wai-aria-1.2/#combobox
=> Add aria accessibility properties to PowerSelectMultiple

addon/components/power-select/options.hbs, tests/integration/components/power-select/a11y-test.js
I didn't include this in my previous PR (https://github.com/cibernox/ember-power-select/pull/1481) because I considered it a breaking change but since there is a plan to cut a new major release of EPS, I may as well try to sneak this in.
I haven't seen any documentation that using `role="alert"` is appropriate here (if such documentation exists, please send it to me!). The W3C reference implementation uses `role="option"` for all options (https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html). In fact, our product had an accessibility audit completed by an external company and they said we had to switch it from `role="alert"`. As well, with the addition of `aria-activedescendant`, screen readers should be able to read out options without this.
We were able to …
=> Use role=option for all options in list

.github/workflows/ci.yml, addon/components/power-select-multiple.hbs, addon/components/power-select-multiple/trigger.hbs, addon/components/power-select.hbs, addon/components/power-select.ts, addon/components/power-select/options.hbs, addon/components/power-select/trigger.hbs, config/ember-try.js, package-lock.json, package.json, tests/dummy/app/templates/components/navigable-select.hbs.bak, tests/dummy/app/templates/components/selected-item-country.hbs, tests/dummy/app/templates/helpers-testing.hbs, tests/dummy/app/templates/public-pages.hbs, tests/dummy/app/templates/public-pages/docs/the-trigger.hbs, tests/dummy/app/templates/snippets/navigable-select-2.hbs.bak, tests/dummy/app/templates/snippets/the-trigger-2.hbs, tests/dummy/app/templates/snippets/the-trigger-4.hbs, tests/integration/components/power-select/customization-with-components-test.js, tests/integration/components/power-select/customization-with-extending-components-test.js
This PR hopefully makes this addon fully embroider compatible.
Note that this relies on https://github.com/embroider-build/embroider/pull/922 (or something along these lines) to be merged - see https://github.com/embroider-build/embroider/issues/921 (in order for embroider compatibility to really work).
This is based on https://github.com/cibernox/ember-power-select/pull/1419 in many ways, but there have been a bunch of changes in the meanwhile, so it was somewhat easier to reproduce the changes than to deal with merge conflicts etc.
I also added some tests to ensure we keep supporting overwriting the default components (which would break with certain implementations, e.g. if we imported the default components in JS-land).
=> Add full embroider compatibility

addon/components/power-select.ts
This commit simplifies the search for the option to scroll to, by querying directly for the element with the right index instead of fetching all elements and then selecting from the generated array.
This feels slightly cleaner to my eyes, and has the added benefit of ensuring it's not broken by something like [vertical-collection](https://github.com/html-next/vertical-collection), which only renders a sliding window of options for performance reasons. The combination was causing keyboard-navigation to fail unexpectedly, since `.item(19)` was no longer guaranteed to be the item with `data-option-index='19'`, nor was the array guaranteed to be long enough to have that element.
=> Cleans up scrollTo's element finding

.github/workflows/ci.yml, README.md, config/ember-try.js
In https://github.com/cibernox/ember-power-select/pull/1533 the default blueprint update just removes the older ember versions from ember-try. If there is no reason to remove them then we can keep testing them and not drop support until we need to 👍 
Also 3.16 is a good base version to support because it's the first Octane LTS so there are no blockers to fully moving everything to Octane (if they haven't already been 😂 )
=> add back ember-try scenarios that were removed with ember-cli-update

addon/components/power-select-multiple/trigger.ts, tests/integration/components/power-select/multiple-test.js
When pressing backspace in a multiple select component there was a console error logged because the selection is undefined: 
Fixed it by just adding a simple nullcheck in the trigger component.
=> Fix error when pressing backspace in empty multiple-select component

addon/components/power-select-multiple/trigger.hbs, app/styles/ember-power-select/base.less, app/styles/ember-power-select/base.scss
ember-a11y-testing (or more specifically, axe) complains that a `<ul>` has to have `<li>` children only.
This PR slightly changes the DOM structure of the multi-select trigger to accomodate that.
I have tried it, and it should look/feel/behave the same!
=> Ensure multiple select <ul> has only <li> children

package.json
Being more permissive on `ember-truth-helpers` helps people migrate their apps/addons.
For example, even ember-basic-dropdown that this addon depends on, does that: https://github.com/cibernox/ember-basic-dropdown/blob/master/package.json#L112
=> be more permissive on ember-truth-helpers

ember-cli-build.js
=> fix: display code snippets in documentation

addon/components/power-select-multiple/trigger.hbs, addon/components/power-select.hbs, addon/components/power-select/before-options.hbs, addon/components/power-select/search-message.hbs, tests/integration/components/power-select/a11y-test.js
This PR fixes (or at least allows to fix) lingering accessibility issues reported by axe (via ember-a11y-testing):
* Pass `aria-label` & `aria-labelled-by` to all search inputs
* Remove `role="combobox"` from search input (See https://github.com/dequelabs/axe-core/issues/1580)
It builds on top of #1305 - I can change that, if required.
With these changes, I could get axe to pass - as long as I added a label, like this:
```hbs
<label id='my-label'>Label here</label>
<PowerSelect
@ariaLabelledBy='my-label'
...
>
```
IMHO it would be nice to add this somewhere to the docs, maybe to the cookbook? But that is a separate issue :)
=> Fix a11y issues with inputs

addon/components/power-select.ts
One should not import from the addon directory. In glint 1.0, this will cause problems if not addressed.
=> Fix import from ember-basic-dropdown

addon/components/power-select.ts
I think the intention here is to `slice` arrays, rather than strings. Arrays can be sorted, but it's not an operation that makes sense for strings.
This caused a regression for a internal object that inherited from `String`. I would perhaps classify it as surprising behaviour.
=> restrict isSliceable to avoid slicing strings

index.js
`app.registry.availablePlugins` doesn't exist in ember cli 5
=> Ember 5 Fix

addon/components/power-select.ts, components/power-select.d.ts
Copied from https://github.com/cibernox/ember-power-select/pull/1577
> For consumers that end up importing this file, the type declarations don't include `/addon`
> 
> `/addon` ends up working during development time, because the original source is in TS -- but it ends up not being the same as the emitted declarations.
This was also previously fixed in https://github.com/cibernox/ember-power-select/pull/1560 but it seems maybe that was accidentally removed in https://github.com/cibernox/ember-power-select/commit/617cceecc560cd5bb63b575b0ccc66ea4b814e33 ?
=> fix: Update invalid type imports

addon/components/power-select.ts
This commit https://github.com/cibernox/ember-power-select/commit/83720b4d27abb4f04a4527769056e8e8fd23df79  introduced a bug for ED 3.27.X users (or earlier versions I guess, idk). HasMany relationships don't implement `.sort`, I think the idea is just to find out if the thing we are dealing with is an Arrayish, I would favor isArray util... which takes into account other ember array-like things
=> isSliceable is not working for ember data 3.x hasmany relationships

.github/workflows/ci.yml, config/ember-try.js, tests/dummy/app/adapters/application.js, tests/integration/components/power-select/ember-data-test.js
While we support ember v3.28, we should also test this version with ember-data 3.28 (see https://github.com/cibernox/ember-power-select/pull/1603)
Added also a test for ember 5 (since the LTS release is coming soon)
=> Use ember-data 3.28 in ember 3.28 test & add ember 5 test

package-lock.json, package.json
The addon is using `did-insert`/ `did-update` modifiers, but `@ember/render-modifiers` was never added in `dependencies`.
The addons has worked since now only, because other packages like `ember-basic-dropdown` were bringing this dependency (in basic-dropdown v7.3.0 we have dropped the dependency `@ember/render-modifiers`)
=> Add missing dependency `@ember/render-modifiers`

docs/app/templates/public-pages/docs/installation.hbs, docs/app/templates/snippets/installation-2.js, docs/package.json, ember-power-select/_index.less, ember-power-select/_index.scss, ember-power-select/ember-power-select.less, ember-power-select/package.json, ember-power-select/scss/bootstrap-complete.scss, ember-power-select/scss/material-complete.scss, ember-power-select/style.scss, ember-power-select/themes/bootstrap.less, ember-power-select/themes/bootstrap.scss, ember-power-select/themes/material.less, ember-power-select/themes/material.scss, pnpm-lock.yaml, test-app/package.json
After migration the addon to V2 the scss/less export for themes was not anymore working like before.
This PR recovers the old import way like discribed in docs
=> Fix theme export for SCSS/LESS & fix primary less file

ember-power-select/src/components/power-select-multiple.ts, ember-power-select/src/components/power-select.ts
If`Element` and `Blocks` is included in the main component interface, `Args` needs its own property.
I had the following glint 2345 error when consuming the PowerSelect component, as it expected Element and Blocks to be passed in as required arguments:
```
NamedArgs<PowerSelectArgs> (…) is missing the following properties from type 'PowerSelectArgs': Element, destination, Blocks glint(2345)
```
=> types: Separate Args and Signature

ember-power-select/package.json, ember-power-select/src/components/power-select/options.hbs, ember-power-select/src/helpers/ember-power-select-is-equal.ts, ember-power-select/src/utils/group-utils.ts, test-app/tests/integration/components/power-select/general-behaviour-test.js, test-app/tests/integration/components/power-select/multiple-test.js, test-app/tests/integration/components/power-select/public-actions-test.js
Fixes: https://github.com/cibernox/ember-power-select/issues/1629
=> Allow to highlight an object option without use the same reference

docs/app/templates/public-pages.hbs, docs/app/templates/public-pages/docs/index.hbs, docs/app/templates/public-pages/docs/styles.hbs, docs/app/templates/public-pages/docs/the-list.hbs, docs/app/templates/public-pages/docs/the-search.hbs, docs/app/templates/public-pages/docs/the-trigger.hbs, docs/package.json, pnpm-lock.yaml
`ember-href-to` supports only ember versions >=3.1 & <3.27. For this reason we should drop it
=> DOCS: Remove `ember-href-to` package & replace usings

ember-power-select/less/base.less, ember-power-select/scss/base.scss, ember-power-select/src/components/power-select-multiple/input.hbs, ember-power-select/src/components/power-select-multiple/input.ts, ember-power-select/src/components/power-select-multiple/trigger.hbs
=> Fix input width in PowerSelectMultiple

ember-power-select/src/components/power-select.ts
To me, all cases of undefined args.options seems to handled well, so undefined options should not give a glint type error.
=> Set `args.options` as optional

ember-power-select/package.json, ember-power-select/src/components/power-select.ts, ember-power-select/src/components/power-select/trigger.hbs, ember-power-select/src/helpers/ember-power-select-is-selected-present.ts, test-app/tests/integration/components/constants.js, test-app/tests/integration/components/power-select/general-behaviour-test.js
solves https://github.com/cibernox/ember-power-select/issues/1673
P.S. please let me know if there is anything else that needs to be done/changed
=> fix: support numbers selection for `PowerSelect` component

docs/app/templates/public-pages/docs/installation.hbs, docs/ember-cli-build.js, docs/package.json, ember-power-select/babel.config.json, ember-power-select/blueprints/ember-power-select/index.js, ember-power-select/package.json, pnpm-lock.yaml, test-app/ember-cli-build.js, test-app/package.json
* Update `ember-concurrency` to v4 (is now a V2 addon)
* Move `ember-concurrency` to peerDependencies -> consumer apps need to do manual steps to get work (see http://ember-concurrency.com/docs/installation -> Configure Babel Transform)
* Add `ember-concurrency` to blueprint
* Added notes for `ember-concurrency` installation in docs (https://ember-power-select.com/docs/installation)
=> Update ember-concurrency to v4 and move to peerDependencies

docs/package.json, ember-power-select/package.json, pnpm-lock.yaml, test-app/package.json, test-app/tests/integration/components/power-select/a11y-test.js
We expect two failing tests because we have overridden `aria-owns` & `aria-controls`, but `ember-basic-dropdown` has never accepeted (https://github.com/cibernox/ember-basic-dropdown/pull/777). This bug was dectected while a11y improvement
=> Update ember-basic-dropdown to 8.0.0-beta.6

ember-power-select/src/components/power-select-multiple.ts
I had an issue popping up in sentry, `Type error: (n.selected || []).slice is not a function` here:  
```ts
defaultBuildSelection(option: any, select: Select) {
const newSelection = (select.selected || []).slice(0);
````
The proposed fix checks for `Array.isArray(select.selected)` in runtime (which should not hurt), but we should probably also fix this by narrowing the type of Select.selected – possibly as a generic of what you pass in to options.
=> fix: `Type error: (n.selected || []).slice is not a function` in multiple select

ember-power-select/src/components/power-select/no-matches-message.hbs
In the `<PowerSelect>` component we call `<NoMatchesMessage>` [with attributes](https://github.com/cibernox/ember-power-select/blob/master/ember-power-select/src/components/power-select.hbs#L171-L173), but the `<NoMatchesMessage>` component is missing splattributes so they don't get rendered.
The example below uses the `helpers-testing-single-power-select` instance in the `test-app` with either a `@labelText="Label"` or an `@ariaLabel="Label"` provided to the `<PowerSelect>`.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
</td><td>
</td></tr>
</table>
Before
```html
<ul class="ember-power-select-options" role="listbox" id="ember-power-select-options-ember74">
<li class="ember-power-select-option ember-power-select-option--no-matches-message" role="option">
No results found
</li> …
```
=> Fix `NoMatchesMessage` component missing splattributes

ember-power-select/src/components/power-select/before-options.hbs
The search input in `BeforeOptions` has a `role="combobox"` which [requires an "aria-expanded" attribute](https://www.w3.org/TR/wai-aria-1.1/#combobox:~:text=Authors%20MUST%20set%20aria%2Dexpanded%20to%20true%20on%20an%20element%20with%20role%20combobox%20when%20it%20is%20expanded%20and%20false%20when%20it%20is%20collapsed.) (set to "true" or "false") depending on the state.
Generally, the `BeforeOptions` is only visible when the PowerSelect is expanded, but since we have access to its state we can use `@select.isOpen` to conditionally apply this value.
The example below uses the `helpers-testing-single-power-select` instance in the `test-app` with either a `@labelText="Label"` or an `@ariaLabel="Label"` provided to the `<PowerSelect>`.
<table>
<tr><th>Before</th><th>After</th></tr> …
=> Fix `BeforeOptions` search input missing `aria-expanded`

ember-power-select/src/components/power-select.hbs
If there are no search results (hence no highlighted index) we currently show a truncated, invalid value for `aria-activedescendant` (for instance `ember74-`). In this PR we propose to only expose a value for `aria-active-descendant` if there are results.
The example below uses the `helpers-testing-single-power-select` instance in the `test-app`.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
</td><td>
</td></tr>
</table>
At @hashicorp we use `<PowerSelect>` extensively and we are grateful to see the many improvements introduced lately.
This change is primarily motivated by the desire to further improve the accessibility compliance of this component – in this instance, by providing a valid value for `aria-active-descendant`.
=> Fix `BeforeOptions` search input having invalid `aria-activedescendant` when no results are found

ember-power-select/rollup.config.mjs
Starting with beta v8.0.0.beta.6 there was missing the `styles.js` export
fix #1738
=> Fix rollup config (style.js -> styles.js)

docs/app/templates/public-pages/docs/migrate-7-0-to-8-0.hbs, ember-power-select/src/helpers/ember-power-select-is-equal.ts
Add helper renaming to upgrade docs and make this helper as public.
As reported in #1738 this helper was already used by apps outside of our components.
It make also sense to use this helper for custom components, otherwise they need to replicate our code parts.
=> Mark ember-power-select-is-equal as public & add as note in migrate docs

docs/app/components/snippets/action-handling-3.hbs, docs/app/components/snippets/action-handling-3.js, docs/app/components/snippets/create-custom-options-1.js, docs/app/controllers/public-pages/cookbook/create-custom-options.js, ember-power-select/src/utils/group-utils.ts, test-app/tests/integration/components/power-select/general-behaviour-test.js, test-app/tests/integration/components/power-select/keyboard-control-test.js, test-app/tests/integration/components/power-select/multiple-test.js
Ember.Array will be deprecated / removed early / later.
For this reason we should already avoid this using.
See:
https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-array-prototype-extensions.md
=> Remove last Ember.Array (A()) using in addon, examples & tests

ember-power-select/package.json, ember-power-select/src/components/power-select-multiple/trigger.hbs, ember-power-select/src/components/power-select-multiple/trigger.ts, ember-power-select/src/components/power-select.hbs, ember-power-select/src/components/power-select.ts, ember-power-select/src/components/power-select/before-options.hbs, ember-power-select/src/components/power-select/before-options.ts, ember-power-select/src/components/power-select/options.hbs, ember-power-select/src/components/power-select/options.ts, pnpm-lock.yaml, test-app/app/components/custom-group-component.hbs, test-app/app/components/custom-group-component.js
This PR removes all usages from `@ember/render-modifiers`.
`@ember/render-modifiers` were meant as a transitional tool from the pre-Octane era, and not long-term usage.
See: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-at-ember-render-modifiers.md
This changes are not braking.
For apps, which have called our old actions in there custom components, there were added deprecation warnings with notes how they must replace until v9
=> Use `ember-modifier` instead of `@ember/render-modifiers`

docs/package.json, pnpm-lock.yaml
The current `ember-data` version brakes docs page. We don't use any `ember-inflector` but `ember-data` brakes production build when there is not installed
This PR fix for the moment our docs build without downgrading `ember-data` (see https://github.com/emberjs/data/issues/9501)
The error occurs only in production build, `ember test` or also with `ember s` there works fine
=> Add `ember-inflector` in docs to fix docs page (cause ember-data bug)

.github/workflows/push-dist.yml
Discoverd that there is atm missing the dist push, which was added in addon-blueprint
=> Add push dist workflow

docs/app/templates/public-pages/docs/api-reference.hbs, ember-power-select/src/components/power-select.hbs, ember-power-select/src/components/power-select.ts
- Adds the `@rootEventType` to be passed on to `BasicDropdown`
- Sets the default value of `@rootEventType` to `mousedown`
- Add documentation
I noticed that we set `eventType` to a default of `mousedown` for the `ember-basic-dropdown` trigger (see https://github.com/cibernox/ember-power-select/blob/3aec36878c8b2aa9cf335b7a2220ae448c359fa1/ember-power-select/src/components/power-select.hbs#L46C1-L46C47), but we don't set it for `rootEventType`, which is the event used when clicking outside of the dropdown to open/close. I believe these should be in sync and the default of `mousedown` makes sense (it's also how a default HTML `select` behaves).
We ran into this issue because the click event doesn't propagate when the original element is removed from the DOM. Causing selects to not close …
=> Add `@rootEventType` argument and set `mousedown` as default

ember-power-select/src/components/power-select.ts
As discussed in #1819 we should use the type from ember-basic-dropdown which was introduced in v8.2.0
=> Use correct typing for rootEventType

ember-power-select/src/components/power-select-multiple/trigger.ts
Discovered in one of my glint projects that we have in multiple trigger the parameter `Element`.
This brings some issues.
1. The paramter is required and you need to pass a `HTMLElement` which is unused
2. you need to add `template-lint-disable no-capital-arguments`, because parameters in uppercase are not allowed
This bug was maybe introduced when there was added glint inside power select
We can safely remove this parameter
=> Remove incorrect `Element` from args in `PowerSelectMultipleTrigger`

ember-power-select/src/components/power-select-multiple.hbs, ember-power-select/src/components/power-select.hbs, ember-power-select/src/components/power-select.ts, test-app/tests/integration/components/power-select/general-behaviour-test.js
ember-basic-dropdown accepts `destinationElement` argument and power-select should to support it as well.
=> Pass destinationElement to basic-dropdown

docs/app/components/snippets/the-search-2.hbs, docs/app/components/snippets/the-search-8.hbs, docs/app/components/snippets/the-search-8.js, docs/app/components/snippets/the-search-9.hbs, docs/app/components/snippets/the-search-9.js, docs/app/controllers/public-pages/docs/the-search.js, docs/app/templates/public-pages/docs/api-reference.hbs, docs/app/templates/public-pages/docs/the-search.hbs, ember-power-select/less/base.less, ember-power-select/package.json, ember-power-select/scss/base.scss, ember-power-select/src/components/power-select-multiple.hbs, ember-power-select/src/components/power-select-multiple/trigger.hbs, ember-power-select/src/components/power-select-multiple/trigger.ts, ember-power-select/src/components/power-select.hbs, ember-power-select/src/components/power-select.ts, ember-power-select/src/components/power-select/before-options.hbs, ember-power-select/src/components/power-select/before-options.ts, ember-power-select/src/components/power-select/input.hbs, ember-power-select/src/components/power-select/input.ts, ember-power-select/src/components/power-select/trigger.hbs, ember-power-select/src/components/power-select/trigger.ts, test-app/tests/integration/components/power-select/general-behaviour-test.js, test-app/tests/integration/components/power-select/multiple-test.js
Follow-up on #1752 & #1784, gradually introducing `@searchFieldPosition` (`before-options` | `trigger`).
<table>
<tr><th>Single-selection</th><th>Multi-selection</th></tr>
<tr><td width="50%">
<code>@searchFieldPosition="before-options"</code> (default)<br />
<code>@searchFieldPosition="trigger"</code>(NEW)<br />
</td><td width="50%">
<code>@searchFieldPosition="trigger"</code> (default)<br />
<code>@searchFieldPosition="before-options"</code>(NEW)<br />
</td></tr>
</table>
`<PowerSelect />` instances will have `@searchFieldPosition` set to `before-options` by default with the option to change it to `trigger`.
`<PowerSelectMultiple />` instances will have `@searchFieldPosition` set to `trigger` by default with the option to change it to `before-options`.
Demo of the new option you will …
=> Add `@searchFieldPosition` argument

ember-power-select/src/components/power-select-multiple/input.ts
…fixes cases where the result of `get(lastSelection, this.args.searchField)` is not guaranteed to be a string
see https://github.com/cibernox/ember-power-select/issues/1854#issuecomment-2551863511
close #1854
=> Fix multiple select error `TypeError Cannot read properties of null (reading 'length')`

ember-power-select/src/components/power-select.hbs, ember-power-select/src/components/power-select.ts, ember-power-select/src/components/power-select/input.hbs, test-app/app/components/custom-trigger-with-search.ts
Similare like in multiple select we need to set some area tags only when dropdown is open and also set the `tabindex` to `-1` for trigger field when the search field is inside trigger.
This solves some a11y issues which we can see in chrome lighthouse
=> Fix a11y error for single select with search field position trigger

ember-power-select/src/components/power-select-multiple.hbs, ember-power-select/src/components/power-select/before-options.hbs, pnpm-lock.yaml, test-app/app/components/custom-multiple-before-options.hbs, test-app/app/components/custom-multiple-before-options.ts, test-app/package.json, test-app/tests/integration/components/power-select/customization-with-components-test.js, test-app/types/global.d.ts
fix #1881
This should fix the search field issue when somebody has used `PowerSelectBeforeOptions` component outside the addon but doesn't pass `@searchFieldPosition` as property to the component now. Bug was introduced [here](https://github.com/cibernox/ember-power-select/pull/1864/files#diff-89a31b278e584b37152993168044f0903d962eecaaf21a08bb5ca6f2b2bc5638R1), starting with v8.6
=> Fix before options component (add input when position is undefined) & Add tests for `@beforeOptionsComponent` with search field

ember-power-select/src/components/power-select/input.hbs, ember-power-select/src/components/power-select/input.ts
fix #1883
When the input field is in trigger, we should only clear the value, when dropdown is not opened
=> Inputfield in trigger - Avoid clearing input field when dropdown is open

docs/app/components/snippets/action-handling-6.js, docs/app/components/snippets/debounce-searches-1.js, docs/package.json, ember-power-select/package.json, ember-power-select/src/components/power-select-multiple/trigger.ts, ember-power-select/src/components/power-select.ts, ember-power-select/src/components/power-select/before-options.ts, ember-power-select/src/components/power-select/input.ts, pnpm-lock.yaml, test-app/tests/integration/components/power-select/general-behaviour-test.js
- `ember-lifeline` is unmaintained, and is already triggering deprecation warnings in newer Ember versions
- The recommendation to use it is outdated, see [this issue](https://github.com/ember-cli/eslint-plugin-ember/issues/2185)
- `ember-power-select` is widely used, so the less dependencies the better
In `test-app` will drop `ember-lifeline` after TS improvements, to avoid merge conflicts (test-app was converted in other PR to TS)
=> Remove use of `ember-lifeline` (addon & docs)

test-app/tests/integration/components/power-select/multiple-modern-test.js
This is a copy of multiple tests, by using modern way (`<PowerSelect @multiple={{true}}>`) instead `<PowerSelectMultiple>` introduced in #1939
=> Copy multiple tests

ember-power-select/src/components/power-select/input.ts
This is a incident, which is already longer time, but comes up after merging multiple with single... the auto focus from search input field is only planned when the field is in `before-options`
=> Add check to avoid auto focus for input field in trigger
