cibernox/ember-power-select

- index.js
> Invoke contentFor hook of dependencies

- blueprints/ember-power-select/index.js
I thought this was fixed, but then I saw #36. Blueprint should work now.
> blueprint fix workaround. closes #36

- tests/dummy/app/index.html
I was seeing an ugly arial font, until I found out why.
> add lato font

- addon/components/ember-power-select/base.js
- addon/components/ember-power-select/multiple.js
- addon/components/ember-power-select/single.js
- addon/templates/components/ember-power-select/multiple.hbs
- addon/templates/components/ember-power-select/single.hbs
- tests/dummy/app/templates/legacy-demo.hbs
- tests/integration/components/ember-power-select-test.js
> Open single select with up and down arrows

- vendor/ember-power-select.css
as discussed in slack, this seems like it could be a sane default.
> increase z index of dropdown content

- vendor/ember-power-select.css
i just noticed that the class i changed was incorrect. I've put 999 here as this is what worked for us. I have no idea what a sane default for this value is.
> change the z index on the correct class

- addon/components/ember-power-select.js
- addon/components/ember-power-select/multiple.js
- addon/components/ember-power-select/multiple/selected.js
- addon/components/ember-power-select/single/selected.js
- addon/templates/components/ember-power-select/multiple.hbs
- addon/templates/components/ember-power-select/multiple/selected.hbs
- addon/templates/components/ember-power-select/single.hbs
- addon/templates/components/ember-power-select/single/selected.hbs
- app/components/ember-power-select/multiple/selected.js
- app/components/ember-power-select/single/selected.js
- tests/dummy/app/templates/legacy-demo.hbs
{{ember-power-select/single/selected}} and {{ember-power-select/multiple/selected}}
They can be replaced by the user
> Create components to encapsulate selected item logic

- addon/components/ember-power-select/multiple/selected.js
- addon/templates/components/ember-power-select/multiple.hbs
- addon/templates/components/ember-power-select/multiple/selected.hbs
- tests/dummy/app/templates/legacy-demo.hbs
- tests/integration/components/ember-power-select-test.js
> Add placeholder support to select multiple

- addon/components/ember-power-select/multiple/selected.js
- app/components/ember-power-select.js
- app/components/power-select.js
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/components/navigable-select.hbs
- tests/dummy/app/templates/cookbook.hbs
- tests/dummy/app/templates/cookbook/navigable-select.hbs
- tests/dummy/app/templates/docs.hbs
- tests/dummy/app/templates/docs/action-handling.hbs
- tests/dummy/app/templates/docs/asynchronous-search.hbs
- tests/dummy/app/templates/docs/disable-things.hbs
- tests/dummy/app/templates/docs/groups.hbs
- tests/dummy/app/templates/docs/how-to-use-it.hbs
- tests/dummy/app/templates/docs/multiple-selection.hbs
- tests/dummy/app/templates/docs/the-list.hbs
- tests/dummy/app/templates/docs/the-search.hbs
- tests/dummy/app/templates/docs/the-trigger.hbs
- tests/dummy/app/templates/legacy-demo.hbs
- tests/integration/components/power-select-test.js
> Rename {{ember-power-select}} to just {{power-select}}

- app/styles/ember-power-select.scss
Color variable `$ember-power-select-text-color` was not used. Here the variable is set to `inherit` and used in the dropdown and the trigger.
> Change and add color variable

- addon/components/power-select/base.js
- addon/components/power-select/multiple.js
- addon/templates/components/power-select/multiple.hbs
This might be backwards incompatible. 
This will be released in v0.4
> Remove wrapper div.

- addon/components/power-select/base.js
- addon/components/power-select/multiple.js
- addon/components/power-select/single.js
- addon/templates/components/power-select/multiple.hbs
- addon/templates/components/power-select/single.hbs
- app/styles/ember-power-select.scss
- package.json
- tests/dummy/app/styles/components/main-header.scss
- tests/integration/components/power-select-test.js
> Several improvements

- addon/components/power-select/single.js
No idea when I left this behind ¯\_(ツ)_/¯
> Remove unused code.

- CHANGELOG.md
- addon/components/power-select.js
- addon/helpers/ember-power-select-option-classes.js
- addon/templates/components/power-select.hbs
- addon/templates/components/power-select/multiple.hbs
- addon/templates/components/power-select/multiple/selected.hbs
- addon/templates/components/power-select/options.hbs
- addon/templates/components/power-select/single.hbs
- addon/templates/components/power-select/single/selected.hbs
- app/styles/ember-power-select.scss
- app/styles/ember-power-select/variables.scss
- package.json
- tests/dummy/app/styles/components/main-header.scss
- tests/dummy/app/templates/components/main-header-select-trigger.hbs
- tests/integration/components/power-select-test.js
- The triangle is no longer a background image, but a <span> tag you
can manipulate in more complex ways.
- Classes (and styles) have been modified to be more BEM (not fully BEM,
but they do have `––modifier`), avoiding class name collisions and making
some selectors more flat.
> Prepare version 0.5.0

- addon/components/power-select/base.js
- addon/components/power-select/multiple.js
- addon/components/power-select/multiple/selected.js
- addon/components/power-select/single.js
- package.json
- tests/dummy/app/components/navigable-select.js
- tests/dummy/app/templates/cookbook/navigable-select.hbs
- tests/integration/components/power-select-test.js
The yielded component dropdown changed it's structure to distinquish
state from actions
> Update to ember-basic-dropdown#0.6.0

- addon/components/power-select/base.js
- tests/integration/components/power-select-test.js
* The passed options are displayed while the user doesn't perform any search.
* When the user performs the first request the options are still visible but the `Loading options...`
message appears
* As soon as the promise returned by the `search` actions is resolved the new results replace the old.
* The `search` action can not return a promise and just update the `options` instead. That works
but unless `options` is a promise the component can't show the loading message.
> Ensure that `options` AND `search` work fine together.

- CHANGELOG.md
- index.js
- package.json
Also relax version of hash polyfill
> Add mising `this._super.included(app);` to included hook

- app/styles/ember-power-select.scss
- package.json
- tests/dummy/app/controllers/cookbook.js
- tests/dummy/app/controllers/docs.js
- tests/integration/components/power-select-test.js
* Fixed styles when the dropdown is rendered in place.
* Fixed position calculation in firefox (done in ember-basic-dropdown)
* Fixed class when a specific `dropdownPosition` is given (done in ember-basic-dropdown)
* Add anti-regression tests.
* Fixed broken links in docs.
> Fix many visual bugs:

- CHANGELOG.md
- addon/components/power-select/multiple.js
- addon/components/power-select/single.js
- addon/templates/components/power-select.hbs
- tests/dummy/app/controllers/docs/action-handling.js
- tests/dummy/app/templates/docs/action-handling.hbs
- tests/integration/components/power-select-test.js
Open question:
* How should we prevent the default bevavior? I did it by checking
if the event was default-prevented by the user, but return false
from the actions is also a valid option.
> Add `onkeydown` action to multiple selects

- addon/components/power-select/base.js
- test-support/helpers/ember-power-select.js
- tests/.jshintrc
- tests/acceptance/helpers-test.js
For some reason `elementId` is not reliable :(
> Generate unique classes for both trigger and dropdown that can be used in tests

- app/styles/ember-power-select.scss
- app/styles/ember-power-select/variables.scss
Add a sass variable to change the border for elements that have the multiple option class.
> add sass variable for the class multiple options

- app/styles/ember-power-select.scss
- app/styles/ember-power-select/variables.scss
- tests/dummy/app/templates/docs/multiple-selection.hbs
Added a couple more sass variables to handle padding for the trigger classes and the multiple option class. Also fixed a small typo.
> Few more sass variables and a typo fix

- addon/components/power-select-multiple/options.js
- addon/components/power-select-multiple/trigger.js
- addon/components/power-select.js
- addon/components/power-select/before-options.js
- addon/components/power-select/options.js
- addon/helpers/ember-power-select-build-selection.js
- addon/templates/components/power-select.hbs
- addon/templates/components/power-select/options.hbs
- app/helpers/ember-power-select-build-selection.js
Need to measure performance before merging
> Simplify customization of slots and centralize closeOnSelect logic

- CHANGELOG.md
- addon/components/power-select.js
- package.json
- tests/dummy/app/controllers/legacy-demo.js
- tests/dummy/app/templates/legacy-demo.hbs
- tests/integration/components/power-select/public-actions-test.js
> Fix functions in public API

- CHANGELOG.md
- package.json
- tests/dummy/app/templates/legacy-demo.hbs
- tests/integration/components/power-select/disabled-test.js
- tests/integration/components/power-select/multiple-test.js
> Remove tabindex completely when the component is disabled

- app/styles/ember-power-select.scss
Should I even care about IE9 anymore?
> Improve styles of multiple select on browsers that support flexbox.

- addon/components/power-select.js
- addon/templates/components/power-select.hbs
- package.json
- test-support/helpers/ember-power-select.js
- tests/integration/components/power-select/general-behaviour-test.js
This is a necessary step for a11y
> Each trigger has a unique id derived from the elementId of the parent select

- tests/dummy/app/controllers/public-pages/cookbook/debounce-searches.js
> Specify scheme in autocomplete example

- CHANGELOG.md
- addon/templates/components/power-select.hbs
- tests/integration/components/power-select/custom-search-test.js
- tests/integration/components/power-select/general-behaviour-test.js
> Added special classes to special options

- bower.json
- package.json
- test-support/helpers/ember-power-select.js
> Update to Ember Basic Dropdown with fastboot support

- test-support/helpers/ember-power-select.js
- tests/acceptance/helpers-test.js
- tests/dummy/app/controllers/helpers-testing.js
- tests/dummy/app/templates/helpers-testing.hbs
> Make test helper async.

- package.json
This makes animations easier to apply thanks to a new `--transitioning-in` class.
Demo: https://ember-power-select.development.pagefrontapp.com/
> Depend on version of EPS with better animations

- CHANGELOG.md
- addon/components/power-select-multiple/trigger.js
- addon/templates/components/power-select-multiple/trigger.hbs
- test-support/helpers/ember-power-select.js
- tests/integration/components/power-select/multiple-test.js
This also adds event delegation for removing elements, so it might have a very minimal perf improvement.
> Allow to remove selected options from multiple selects with touch events

- addon/components/power-select-multiple.js
- addon/components/power-select-multiple/options.js
- app/components/power-select-multiple/options.js
The generic one is enough now that how the new selection is build
it done by a passed in function.
> Remove power-select-multiple/options component.

- tests/acceptance/all-public-pages-test.js
This kind of acceptance test is useful because it warns you if there are exceptions thrown while trying to render any of the public pages.
> Added acceptance tests that visit all public pages

- .travis.yml
- addon/components/power-select.js
This ensures action are consistent.
Closes #364
> Public API should call the same actions available for the templates.

- addon/components/power-select/options.js
- tests/integration/components/power-select/mouse-control-test.js
> Customized Options: fixed selection closes #389

- test-support/helpers/ember-power-select.js
- tests/.jshintrc
- tests/acceptance/helpers-test.js
- tests/dummy/app/templates/helpers-testing.hbs
- tests/dummy/app/templates/public-pages/docs/test-helpers.hbs
- tests/integration/components/power-select/custom-search-test.js
with tests and docs updated.  Had to reset one test b/c test run was failing on one commit after wait helper commit.
> Test Helpers: removeMultipleOption and clearSelected

- addon/components/power-select/options.js
added check for 0 index item on optionItem for mouseover and mouseup
https://github.com/cibernox/ember-power-select/issues/402
> added check for 0 index item on optionItem

- CHANGELOG.md
- addon/templates/components/power-select/trigger.hbs
- tests/integration/components/power-select/general-behaviour-test.js
> [BUGFIX] Disabled selects should not be clearable

- CHANGELOG.md
- addon/components/power-select.js
- addon/templates/components/power-select.hbs
- package.json
- tests/dummy/app/models/user.js
- tests/dummy/mirage/config.js
- tests/dummy/mirage/models/user.js
- tests/dummy/mirage/serializers/user.js
- tests/integration/components/power-select/ember-data-test.js
- tests/integration/components/power-select/general-behaviour-test.js
> Make selected promise aware

- addon/components/power-select.js
- tests/integration/components/power-select/general-behaviour-test.js
see https://github.com/cibernox/ember-power-select/pull/420#issuecomment-204337797
> make sure we do not overwrite new selected promise values

- addon/components/power-select.js
- addon/templates/components/power-select.hbs
- tests/dummy/app/templates/public-pages/docs/api-reference.hbs
- tests/integration/components/power-select/check-horizontal-position-test.js
> pass horizontalPosition through basic-dropdown component

- CHANGELOG.md
- addon/components/power-select.js
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/public-pages/docs/the-list.hbs
- tests/integration/components/power-select/disabled-test.js
> [BUGFIX] Avoid highlight disabled options after search

- addon/templates/components/power-select-multiple.hbs
I forgot about multiple component
> pass horizontalPosition through power-select-multiple

- CHANGELOG.md
- package.json
- tests/dummy/app/templates/public-pages/docs/api-reference.hbs
- tests/integration/components/power-select/check-horizontal-position-test.js
- vendor/ember-power-select-bootstrap.css
- vendor/ember-power-select.css
> add test for multiple component

- .travis.yml
- addon/components/power-select.js
- addon/components/power-select/trigger.js
- addon/templates/components/power-select/trigger.hbs
- tests/integration/components/power-select/disabled-test.js
- tests/integration/components/power-select/general-behaviour-test.js
It's not its resposability to do such things
> [BUGFIX] Avoid `select` action to stopPropagation or preventDefault.

- tests/dummy/app/templates/public-pages/docs/test-helpers.hbs
Issue: https://github.com/cibernox/ember-power-select/issues/391
> DOCS - Integration Tests

- test-support/helpers/ember-power-select.js
Some fixes for the jshint warnings I got when `ember-power-select` copied this file into my project `tests/helpers` folder.
> Remove jshint warnings

- addon/components/power-select/options.js
- test-support/helpers/ember-power-select.js
- tests/integration/components/power-select/touch-control-test.js
> Customized Options: fixed selection on touch devices

- package.json
> Run before ember-cli-sri

- test-support/helpers/ember-power-select.js
- tests/acceptance/helpers-test.js
- tests/dummy/app/controllers/helpers-testing.js
- tests/dummy/app/templates/helpers-testing.hbs
Makes the test helper function async friendly by adding wait calls.
Closes #507
> Make removeMultipleOption and clearSelected async friendly

- addon/components/power-select.js
- addon/templates/components/power-select.hbs
- app/styles/ember-power-select.scss
- package.json
- tests/acceptance/helpers-test.js
- tests/dummy/app/templates/helpers-testing.hbs
- tests/dummy/app/templates/public-pages.hbs
- tests/integration/components/power-select/check-horizontal-position-test.js
- tests/integration/components/power-select/disabled-test.js
- tests/integration/components/power-select/general-behaviour-test.js
- tests/integration/components/power-select/multiple-test.js
> Update to brand new EBD

- addon/templates/components/power-select.hbs
- tests/integration/components/power-select/public-actions-test.js
> Fix keydown not being called in multiple-selects for A-Z

- app/styles/ember-power-select.scss
- tests/dummy/app/templates/legacy-demo.hbs
Also some unused styles were removed and others flattened.
> Fix render-in-place width

- addon/components/power-select.js
- tests/integration/components/power-select/a11y-test.js
> Remove CP for tagName

- addon/components/power-select.js
- tests/integration/components/power-select/keyboard-control-test.js
Pressing space on selects without a searchbox does it.
> Pressing SPACE on searchboxes doesn't select the highlighted

- CHANGELOG.md
- addon/components/power-select-multiple/trigger.js
It has been broken since 1.0.0 probably.
> [BUGFIX] Fix search box width calculation

- CHANGELOG.md
- addon/templates/components/power-select.hbs
- package.json
- tests/integration/components/power-select/general-behaviour-test.js
Added test to prevent future regressions
> [BUGFIX] Fix `destination=foo`. Broke in 1.0.0 refactor.

- addon/components/power-select.js
prevent accidentally resetting results when options are opdate with no changes
> prevent accidentally resetting results 

- index.js
- tests/dummy/app/templates/public-pages/cookbook/bootstrap-theme.hbs
```
var app = new EmberApp(defaults, {
'ember-power-select': {
theme: false
}
});
```
> Allow disabling styles when not using Sass

- CHANGELOG.md
- addon/components/power-select/before-options.js
- tests/dummy/app/templates/public-pages/docs/the-search.hbs
- tests/integration/components/power-select/general-behaviour-test.js
> Added optionally "autofocus" property to before-options component.

- addon/components/power-select.js
For now they are private API only.
> Move `activeSearch` and `expirableSearchText` to the publicAPI object.

- CHANGELOG.md
- package.json
- tests/integration/components/power-select/disabled-test.js
> Fix reenable component after it has been disabled

- addon/templates/components/power-select-multiple/trigger.hbs
- tests/integration/components/power-select/multiple-test.js
> placeholder when search disabled and no items

- app/styles/ember-power-select.scss
> Don't pollute ember-basic-dropdown styles

- addon/utils/group-utils.js
Ember.A doesn't work yet due to https://github.com/ember-fastboot/ember-cli-fastboot/issues/251
> Replace Ember.A with a manual check for fastboot compat

- tests/dummy/app/templates/public-pages/addons/index.hbs
Some of the copy on this page felt off to me. This is just a proposed change to that language
> Adjust copywriting on public-pages/addon/index

- CHANGELOG.md
- package.json
> Prevent open/close action on destroyed component by updating EBD

- addon/components/power-select.js
- addon/templates/components/power-select-multiple.hbs
- addon/templates/components/power-select-multiple/trigger.hbs
- addon/templates/components/power-select.hbs
- tests/dummy/app/controllers/legacy-demo.js
- tests/dummy/app/templates/legacy-demo.hbs
- tests/dummy/app/templates/public-pages/docs/action-handling.hbs
- tests/dummy/app/templates/public-pages/docs/api-reference.hbs
- tests/integration/components/power-select/public-actions-test.js
> Add `onblur` action for symmetry with `oninput`

- tests/dummy/app/templates/public-pages/docs/how-to-use-it.hbs
Makes this a little easier to read as a native English speaker.  Thanks again for all your work here! ❤️
> Tweaks to grammer

- tests/dummy/app/styles/components/main-header.scss
> Fix styles of select in navbar

- package.json
- yarn.lock
This update is not required if people update their node_modules, but this also makes it explicit.
> Update EBD to finally work well in touch devises

- package.json
Support node-sass v4.1.0 Alphine linux
> Update ember-cli-sass v6.0.0

- index.js
> Use es6 syntax in node

- addon/components/power-select-multiple.js
- addon/components/power-select.js
- addon/helpers/ember-power-select-is-selected.js
- package.json
- tests/integration/components/power-select/general-behaviour-test.js
- tests/integration/components/power-select/multiple-test.js
- yarn.lock
This offers an scape valve when ensuring the same object reference is
preserved is hard.
Closes #773
> [FEATURE] If options implement the `isEqual` method, EPS will use it

- .jshintignore
- .npmignore
- .template-lintrc.js
- config/deploy.js
- config/ember-try.js
- config/environment.js
- config/release.js
- ember-cli-build.js
- index.js
- run-fastboot-tests.js
- testem.js
- tests/dummy/config/environment.js
My IDE was a bit complaining, so another big time PR! ;)
> remove jshint remains

- addon/templates/components/power-select.hbs
- package.json
- yarn.lock
This requires an intermediate version bump?
> Adapt to consistent casing in EmberBasicDropdown 0.20.0

- addon/templates/components/power-select.hbs
- tests/dummy/app/templates/components/list-of-countries.hbs
- tests/integration/components/power-select/customization-with-compoments-test.js
add extra hash to options component
> add extra hash to options component

- CHANGELOG.md
- addon/templates/components/power-select-multiple.hbs
- addon/templates/components/power-select.hbs
- package.json
- tests/dummy/app/templates/public-pages/docs/api-reference.hbs
- tests/integration/components/power-select/customization-with-attrs-test.js
- tests/integration/components/power-select/general-behaviour-test.js
- yarn.lock
> [FEATURE] Allow to customise trigger’s id

- index.js
- yarn.lock
The build (in EPSWFB) was failing due to `app.import is not a function` in index.js of EPS.
Add an extra layer that checks if the app is located in `app.parent.app`.
> Fix app.import bug

- test-support/helpers/ember-power-select.js
- tests/integration/helpers-test.js
> Add an optional scope to typeInSearch test helper

- addon/components/power-select.js
- addon/templates/components/power-select.hbs
This would be helpful, especially for ember-paper.
> add the possibility to customize ebd trigger tagName

- addon/components/power-select.js
- addon/templates/components/power-select.hbs
in order for us to be able to take advantage of https://github.com/cibernox/ember-basic-dropdown/pull/236
> allow to specify ebd content tag name

- package.json
- yarn.lock
People using EPS will not have any breaking change
> Update EBD with breaking change that never surfaced EPS's api

- package.json
Chrome failing for onfocus/onblur events (integration).  Phantomjs passing.
> [EMBER]: upgrade deps to 2.12

- addon/components/power-select.js
> Abort scrollTo if element to scroll is null

- CHANGELOG.md
- addon/components/power-select.js
- tests/dummy/app/templates/public-pages/docs/groups.hbs
- tests/integration/components/power-select/assertions-and-deprecations-test.js
- tests/integration/components/power-select/groups-test.js
/cc @offirgolan This would have helped you I think
> Add dev/test assertion to tell users that promises inside groups are not allowed.

- app/styles/ember-power-select.less
- app/styles/ember-power-select.scss
- tests/dummy/app/styles/app.scss
- vendor/ember-power-select-bootstrap.css
- vendor/ember-power-select-material.css
- vendor/ember-power-select.css
This has been bugging me in my application for a while!
This resolves the momentum scrolling issues on iOS devices, have tested it on my iPhone 5 running iOS 10.3.1.
Fixes #841
> Fix momentum scrolling issue on iOS devices

- addon/components/power-select/options.js
Fixes https://github.com/cibernox/ember-power-select/issues/919
> Fix iOS issue with touchend event

- addon/components/power-select-multiple.js
- addon/components/power-select.js
- addon/helpers/ember-power-select-is-selected.js
- test-support/helpers/ember-power-select.js
- tests/dummy/app/components/navigable-select.js
- tests/helpers/start-app.js
- yarn.lock
The only missing things are `Ember.testing` and `Ember.Test`
> Add more shims

- tests/dummy/app/templates/public-pages/addons/index.hbs
ember-cli-time-picker leverages the awesome ember-power-select component.
> Add link to ember-power-timepicker component in the public web site

- addon/templates/components/power-select.hbs
- tests/integration/components/power-select/customization-with-components-test.js
Referencing:
https://github.com/cibernox/ember-power-select-typeahead/pull/61
> [TRIGGER]: loadingMessage passed to triggerComponent

- addon/components/power-select.js
- tests/integration/components/power-select/mouse-control-test.js
> Don't validate Y axis in testing

- addon/components/power-select.js
- tests/integration/components/power-select/general-behaviour-test.js
> If the options are a PromiseArrayProxy, set the options to the initial value and update later

- addon/components/power-select.js
- addon/templates/components/power-select-multiple.hbs
- addon/templates/components/power-select.hbs
- tests/dummy/app/templates/public-pages/docs/api-reference.hbs
- yarn.lock
Dependent upon https://github.com/cibernox/ember-basic-dropdown/pull/351
> Pass preventScroll option forward to ember-basic-dropdown.

- package.json
- yarn.lock
- The select shouldn't open with the right button of the mouse
- Potention undefined `e.target` in some edge cases
> Update EBD to 0.34.0 to fix a couple minor issues:

- tests/dummy/app/templates/public-pages/docs/api-reference.hbs
Please review. This PR just removes a duplicated of the word `any` found in the doc.
> Resolves typo.

- addon/templates/components/power-select.hbs
- addon/templates/components/power-select/trigger.hbs
Add extra params on triggers to permit custom select item component.
> Add extra params for trigger

- tests/dummy/app/controllers/public-pages/docs/the-list.js
- tests/dummy/app/templates/public-pages/docs/the-list.hbs
- tests/dummy/app/templates/snippets/the-list-10-js.js
- tests/dummy/app/templates/snippets/the-list-10.hbs
> stop click propagation added to the docs

- addon/components/power-select-multiple/trigger.js
- addon/components/power-select.js
- addon/components/power-select/before-options.js
- addon/components/power-select/options.js
I removed all the self.document and self.window occurrences from the addon
Fixes #1076
> Changed self.window to window and self.document to document

- CHANGELOG.md
- addon/templates/components/power-select-multiple.hbs
- addon/templates/components/power-select.hbs
- tests/integration/components/power-select/general-behaviour-test.js
- tests/integration/components/power-select/multiple-test.js
- yarn.lock
> Bind title to the trigger

- addon/components/power-select.js
- tests/integration/components/power-select/general-behaviour-test.js
Test and possible fix for #1147
> Proxy object detection

- addon/components/power-select/options.js
> Only load polyfill when not in FastBoot environment

- addon/components/power-select/options.js
@cibernox sorry for this oversight.
> fix: typeof returns string, broke polyfill when necessary

- tests/dummy/app/templates/public-pages/support-the-project.hbs
> Change Slack for Discord

- tests/dummy/app/templates/public-pages/docs/how-to-use-it.hbs
- tests/dummy/app/templates/public-pages/support-the-project.hbs
- tests/dummy/app/templates/snippets/how-to-use-it-3-js.js
- tests/dummy/app/templates/snippets/how-to-use-it-3.hbs
Fix build error due to missing "noopener" on target="_blank" link in support-the-project.hbs
> Fix build error

- CONTRIBUTING.md
- tests/dummy/app/templates/public-pages/docs/how-to-use-it.hbs
- tests/dummy/app/templates/public-pages/support-the-project.hbs
- tests/dummy/app/templates/snippets/how-to-use-it-3-js.js
- tests/dummy/app/templates/snippets/how-to-use-it-3.hbs
I have improved the first paragraph to use the active-voice rather than the passive-voice and documented (including an example) now to use a computed property for the `selected` parameter of this component. This PR also includes a fix for the existing build error and updates the contributing.md to use yarn instead of npm and bower.
> Improve documentation

- addon/components/power-select/before-options.js
@offirgolan Check if this fixes your issue.
> Fix inconsistent focus of the input in single selects

- blueprints/ember-power-select/index.js
support module unification blueprint for styles
it helps #1204
> support mu src/ui/styles and app/styles/

- package.json
- yarn.lock
This should help us fixing some issues when using ember canary.
> Upgrade ember-concurrency

- tests/dummy/app/templates/public-pages/docs/the-search.hbs
Seems like a type as this sentence doesn't make sense. Fixing the grammar.
> Fixing broken verbiage in official doc. (search documentation)

- addon/components/power-select/options.js
- tests/integration/components/power-select/disabled-test.js
This PR fixes a problem which allows to select disabled options on touch devices.
> fix disabled options on touch devices

- index.js
> Always call _super.included

- index.js
> Always call _super.included (#1240)

- addon/components/power-select.js
> Guard against select being destroyed.

- CHANGELOG.md
- addon/templates/components/power-select-multiple.hbs
- tests/integration/components/power-select/multiple-test.js
> Fix bug in multiple select with duplicated searchbox

- CHANGELOG.md
Not sure it's worth it, but I would find it useful to have this mentioned
> searchEnabled defaults to false as Breaking change

- addon/components/power-select.js
> Fix bug with Ember-Data collections

- addon-test-support/index.js
Fix for https://github.com/cibernox/ember-power-select/issues/1317
> Add options to arguments for 'warn' (#1317)

- tests/dummy/app/templates/public-pages/docs/action-handling.hbs
> Fix onInput camelCasing in docs.

- README.md
This prevented usage in IE11 for us.
> docs: document an IE11 issue with uglify

- addon/components/power-select.ts
Fixed missing ``target`` argument in calling removeObserver
> Fixes #1362: Error thrown when promise of selected argument changes

- tests/dummy/app/templates/public-pages/docs/the-search.hbs
> quick typo

- addon/components/power-select-multiple.hbs
- addon/components/power-select.hbs
- addon/components/power-select.ts
- addon/components/power-select/no-matches-message.hbs
- app/components/power-select/no-matches-message.js
- tests/dummy/app/templates/public-pages/docs/api-reference.hbs
- tests/integration/components/power-select/customization-with-components-test.js
I tried to add back the customization of no matches message component.
Feel free to comment and ask for modifications.
> Add no matches message component customization

- addon/components/power-select-multiple/trigger.hbs
- tests/dummy/app/templates/playground.hbs
- tests/integration/components/power-select/multiple-test.js
> Prevent the input of the searchbox from submitting the wrapper form.

- addon/components/power-select.ts
> Remove debuggers

- addon/components/power-select-multiple.hbs
Pass in `@animationEnabled` attribute into `<PowerSelect>` from `<PowerSelectMultiple>`.
> Pass in @animationEnabled to PowerSelectMultiple

- package-lock.json
- package.json
With the new 1.x versions, it should be much easier to keep similar addon versions in sync via `^`.
> Update `@embroider/util` to 1.0.0

- addon/utils/group-utils.ts
- test-support.d.ts
- Adds ambient type declarations for `selectChoose` and `selectSearch` test support functions.
- Exports the `Group` data structure interface as a convenience.
> Add type declarations

- addon/components/power-select.hbs
- package-lock.json
- package.json
Fixes https://github.com/cibernox/ember-basic-dropdown/issues/550
This argument is documented in both ember-basic-dropdown and ember-power-select, but never actually used or passed along.
> Pass along the @animationEnabled argument to dropdown.Content, bump ember-basic-dropdown

- addon/components/power-select.ts
> Remove ember-data array deprecation

- tests/integration/components/power-select/customization-with-extending-components-test.js
related to PR https://github.com/cibernox/ember-power-select/pull/1570
> Fix tests for embroider-optimized

- CHANGELOG.md
> Add missing release notes for v7

- README.md
Update compatibility for v7, as we support officially ember v3.28+
> Update compatibility in readme

- docs/app/templates/public-pages/docs/installation.hbs
- docs/ember-cli-build.js
Like discussed in #1607 we show user an additional option to import css
> DOCS: Add additional option for css import

- ember-power-select/_index.scss
> Fix scss import in index.scss

- docs/app/templates/public-pages/cookbook/index.hbs
- docs/app/templates/public-pages/docs/the-search.hbs
- docs/app/templates/snippets/system-wide-config-1-js.js
> DOCS: Fix typo & usings

- ember-power-select/package.json
- pnpm-lock.yaml
- test-app/package.json
Update `ember-assign-helper` is now a V2 addon, the new major version has as dependency only the latest
> Update `ember-assign-helper` to latest

- docs/app/components/snippets/installation-1.scss
In docs there was the scss import statement wrong (reported https://github.com/cibernox/ember-power-select/pull/1637#issuecomment-1899021913)
> DOCS: Fix scss import statement

- ember-power-select/src/components/power-select-multiple.hbs
> Forward @highlightOnHover & @typeAheadOptionMatcher on multiple select

- docs/app/templates/public-pages/docs/migrate-7-0-to-8-0.hbs
- ember-power-select/src/themes/bootstrap.js
- ember-power-select/src/themes/material.js
- ember-power-select/themes/bootstrap.js
- ember-power-select/themes/material.js
> Fix theme imports for vanilla js

- ember-power-select/src/components/power-select.ts
A couple of improvements to the `<PowerSelect>` types
> Type improvements

- docs/.eslintrc.js
- docs/app/components/snippets/action-handling-6.js
- docs/app/components/snippets/debounce-searches-1.js
- docs/app/templates/snippets/test-helpers-1-js.js
- docs/package.json
- ember-power-select/.eslintrc.cjs
- ember-power-select/package.json
- ember-power-select/src/components/power-select-multiple/trigger.ts
- ember-power-select/src/components/power-select.ts
- ember-power-select/src/components/power-select/before-options.ts
- pnpm-lock.yaml
- test-app/.eslintrc.js
- test-app/app/controllers/helpers-testing.js
- test-app/package.json
- test-app/tests/integration/components/power-select/custom-search-test.js
- test-app/tests/integration/components/power-select/disabled-test.js
- test-app/tests/integration/components/power-select/general-behaviour-test.js
- test-app/tests/integration/components/power-select/multiple-test.js
- test-app/tests/integration/components/power-select/public-actions-test.js
Remove all using from `@ember/runloop` with `ember-lifeline`
See: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-runloop.md
> Replace `@ember/runloop` with `ember-lifeline`

- .github/workflows/docs.yml
- docs/404.html
- docs/app/index.html
After moving to Github page we need to add a small script to get work direct entry into sub page
close #1809
> Fix direct links to sub pages

- docs/app/templates/public-pages/docs/installation.hbs
Fixes some grammar mistakes. Makes it a bit easier to read.
> Improve installation documentation text

- docs/package.json
- ember-power-select/package.json
- pnpm-lock.yaml
- test-app/package.json
Reverts cibernox/ember-power-select#1847
> Revert "Allow `@ember/test-helpers` v4 as dependency"

- ember-power-select/src/components/power-select.ts
> Fix empty ariaLabelledBy
